import { createElement as h } from 'react';
import type { RouteDef } from '../../specs/types';
import { EVERYONE } from '../../auth/roles';
import { HomePage } from './HomePage';
import { HowPage } from './HowPage';
import { PricingPage } from './PricingPage';
import { homeSpec, howSpec, pricingSpec } from './specs';

export const routes: RouteDef[] = [
  { path: '/site', element: h(HomePage), spec: homeSpec, roles: EVERYONE, surface: 'public' },
  { path: '/site/how', element: h(HowPage), spec: howSpec, roles: EVERYONE, surface: 'public' },
  { path: '/site/pricing', element: h(PricingPage), spec: pricingSpec, roles: EVERYONE, surface: 'public' },
];

/** EN + ES. Headlines, navigation and CTAs are written in both; the longer explanatory bodies are EN-only and flagged for the Spanish pass (T30). */
export const strings = {
  // chrome
  'site.skip': { en: 'Skip to content', es: 'Saltar al contenido' },
  'site.brand_aria': { en: 'Imagine home', es: 'Inicio de Imagine' },
  'site.nav_aria': { en: 'Main', es: 'Principal' },
  'site.nav_home': { en: 'Home', es: 'Inicio' },
  'site.nav_how': { en: 'How it works', es: 'Cómo funciona' },
  'site.nav_pricing': { en: 'Pricing', es: 'Precios' },
  'site.nav_hub': { en: 'See the hub', es: 'Ver el hub' },
  'site.foot_aria': { en: 'Footer', es: 'Pie de página' },
  'site.foot_tag': { en: 'Operating systems, already built.', es: 'Sistemas operativos, ya construidos.' },
  'site.foot_note': { en: 'Every example on this site is a fictional business we built a full system for. Open any of them and switch roles; nothing is a screenshot.', es: 'Cada ejemplo de este sitio es un negocio ficticio para el que construimos un sistema completo. Ábrelos y cambia de rol; nada es una captura.' },
  // W-01 hero
  'site.hero_eyebrow': { en: 'For small businesses that outgrew their tools', es: 'Para negocios que superaron sus herramientas' },
  'site.h1': { en: 'An operating system, already built for you.', es: 'Un sistema operativo, ya construido para ti.' },
  'site.hero_lede': { en: 'Not a demo of someone else\'s software. We build your system first - your brand, your departments, a view for every role in your business and in your life - and you open it before you pay anything.', es: 'No es la demo del software de otro. Construimos tu sistema primero - tu marca, tus departamentos, una vista para cada rol de tu negocio y de tu vida - y lo abres antes de pagar nada.' },
  'site.get_yours': { en: 'Get yours', es: 'Consigue el tuyo' },
  'site.see_sample': { en: 'See a sample', es: 'Ver un ejemplo' },
  'site.hero_note': { en: 'The samples below are live: open them on your phone, switch roles, print the proposal.', es: 'Los ejemplos están en vivo: ábrelos en tu teléfono, cambia de rol, imprime la propuesta.' },
  'site.sample_switch': { en: 'Choose a sample business', es: 'Elige un negocio de ejemplo' },
  'site.device_phone': { en: '{business} on a phone', es: '{business} en el teléfono' },
  'site.device_laptop': { en: '{business} on a laptop', es: '{business} en el portátil' },
  'site.device_tv': { en: '{business} on the back-office screen', es: '{business} en la pantalla de la oficina' },
  'site.device_cap': { en: 'Live: {business}, {city}', es: 'En vivo: {business}, {city}' },
  'site.device_live': { en: 'live', es: 'en vivo' },
  'site.preview_attention': { en: 'Needs attention', es: 'Requiere atención' },
  'site.preview_month': { en: 'This month', es: 'Este mes' },
  'site.their_page': { en: 'Their page', es: 'Su página' },
  'site.their_demo': { en: 'Their demo', es: 'Su demo' },
  'site.their_proposal': { en: 'Their proposal', es: 'Su propuesta' },
  // W-01 promise
  'site.promise_h2': { en: 'Three steps, and one of them is ours', es: 'Tres pasos, y uno es nuestro' },
  'site.step_n': { en: 'Step {n}', es: 'Paso {n}' },
  'site.step_learn': { en: 'We learn who you are', es: 'Aprendemos quién eres' },
  'site.step_learn_body': { en: 'Your industry, your city, how many people work with you, how many locations, the tools you already pay for. Most of it we find before we ask; the rest is a short conversation.', es: 'Tu industria, tu ciudad, cuánta gente trabaja contigo, cuántas sedes y las herramientas que ya pagas. Casi todo lo encontramos antes de preguntar; el resto es una conversación corta.' },
  'site.step_build': { en: 'We build it', es: 'Lo construimos' },
  'site.step_build_body': { en: 'Your system is composed before the first call: brand, departments, role views, documents, the customer app and the dashboards - on phone, laptop and the screen in the back office.', es: 'Tu sistema se compone antes de la primera llamada: marca, departamentos, vistas por rol, documentos, la app de clientes y los paneles - en teléfono, portátil y la pantalla de la oficina.' },
  'site.step_cut': { en: 'You cut your stack', es: 'Recortas tu stack' },
  'site.step_cut_body': { en: 'One by one the subscriptions go: scheduling, messaging, documents, reporting, the spreadsheet that holds it together. One system, one bill, one place your team learns.', es: 'Una a una se van las suscripciones: agenda, mensajería, documentos, reportes, la hoja de cálculo que lo sostiene todo. Un sistema, una factura, un solo lugar que tu equipo aprende.' },
  // W-01 proof
  'site.proof_h2': { en: 'What it saves', es: 'Lo que ahorra' },
  'site.proof_sub': { en: 'Averages across the {n} systems shown on this page, calculated by the same engine that priced them.', es: 'Promedios de los {n} sistemas de esta página, calculados por el mismo motor que los cotizó.' },
  'site.proof_avg': { en: 'Average net saving', es: 'Ahorro neto medio' },
  'site.proof_tools': { en: 'Tools replaced', es: 'Herramientas reemplazadas' },
  'site.proof_tools_hint': { en: 'per business, on average', es: 'por negocio, en promedio' },
  'site.proof_systems': { en: 'Systems on this page', es: 'Sistemas en esta página' },
  'site.proof_systems_hint': { en: 'all of them live', es: 'todos en vivo' },
  'site.per_year': { en: 'per year', es: 'al año' },
  'site.per_month': { en: 'per month', es: 'al mes' },
  // W-01 samples + pricing teaser
  'site.samples_h2': { en: 'Sample systems', es: 'Sistemas de ejemplo' },
  'site.samples_sub': { en: 'Fictional businesses, real systems', es: 'Negocios ficticios, sistemas reales' },
  'site.team_n': { en: '{n} people', es: '{n} personas' },
  'site.saved_year': { en: 'saved per year', es: 'ahorrado al año' },
  'site.pricing_h2': { en: 'Pricing', es: 'Precios' },
  'site.pricing_all': { en: 'See all bands and the calculator', es: 'Ver todas las bandas y la calculadora' },
  'site.band_starter': { en: 'Starter', es: 'Starter' },
  'site.band_team': { en: 'Team', es: 'Team' },
  'site.band_multi': { en: 'Multi', es: 'Multi' },
  'site.band_starter_who': { en: 'One location, up to 5 people.', es: 'Una sede, hasta 5 personas.' },
  'site.band_team_who': { en: 'One location, up to 25 people.', es: 'Una sede, hasta 25 personas.' },
  'site.band_multi_who': { en: 'Several locations, or more than 25 people.', es: 'Varias sedes, o más de 25 personas.' },
  'site.band_suggested': { en: 'Fits you', es: 'Te corresponde' },
  'site.month': { en: 'month', es: 'mes' },
  'site.pricing_teaser_note': { en: 'One bill replaces the stack. No per-seat surprise: the band is set by your team size and locations.', es: 'Una factura reemplaza el stack. Sin sorpresas por usuario: la banda depende de tu equipo y tus sedes.' },
  'site.cta_h2': { en: 'Your system is one conversation away.', es: 'Tu sistema está a una conversación.' },
  'site.cta_sub': { en: 'Tell us the business; we build it and send you the link.', es: 'Dinos cuál es el negocio; lo construimos y te mandamos el enlace.' },
  // W-02
  'site.how_eyebrow': { en: 'The method', es: 'El método' },
  'site.how_diagram_label': { en: 'How the system is built, as a diagram. Scrolls sideways on small screens.', es: 'Cómo se construye el sistema, en diagrama. Se desplaza de lado en pantallas pequeñas.' },
  'site.how_h1': { en: 'How we build your system before you ask.', es: 'Cómo construimos tu sistema antes de que lo pidas.' },
  'site.how_lede': { en: 'Six steps. The first five happen before you spend a minute with us; the sixth never stops.', es: 'Seis pasos. Los primeros cinco ocurren antes de que nos dediques un minuto; el sexto nunca se detiene.' },
  'site.how_steps_h2': { en: 'The loop', es: 'El ciclo' },
  'site.how_intake': { en: 'Intake', es: 'Intake' },
  'site.how_intake_body': { en: 'We start from what is public: industry, city, team size, locations, the tools mentioned in your job posts. The questions we still need are asked heaviest-first, so five answers get us further than fifty.', es: 'Empezamos con lo público: industria, ciudad, tamaño del equipo, sedes y las herramientas que mencionan tus ofertas de empleo. Las preguntas que faltan se hacen por peso: cinco respuestas rinden más que cincuenta.' },
  'site.how_guess': { en: 'Stack guess', es: 'Estimación del stack' },
  'site.how_guess_body': { en: 'We estimate the software you pay for today - one product per category, scaled by your seats and locations - and what each one costs per month. You correct it; the numbers move as you do.', es: 'Estimamos el software que pagas hoy - un producto por categoría, ajustado a tus usuarios y sedes - y cuánto cuesta cada uno al mes. Tú lo corriges y los números se mueven contigo.' },
  'site.how_compose': { en: 'Compose', es: 'Composición' },
  'site.how_compose_body': { en: 'Your system is composed from that picture: palette, departments, a view per business and life role, documents, the customer app, the dashboards. The page that shows it is composed too, in the shape that suits you.', es: 'Tu sistema se compone con ese retrato: paleta, departamentos, una vista por rol del negocio y de la vida, documentos, la app de clientes y los paneles. La página que lo muestra también se compone, en la forma que te sirve.' },
  'site.how_demo': { en: 'Demo', es: 'Demo' },
  'site.how_demo_body': { en: 'You open it. No form, no sales call first, no "request access". Switch to your manager\'s view, your accountant\'s view, your partner\'s view, on your phone.', es: 'Lo abres. Sin formulario, sin llamada previa, sin "solicitar acceso". Cambia a la vista de tu gerente, de tu contador, de tu pareja, desde tu teléfono.' },
  'site.how_book': { en: 'Book', es: 'Reserva' },
  'site.how_book_body': { en: 'Fifteen minutes, calendar inline, with anyone whose role you want to see. We walk the system and write down every correction as we go.', es: 'Quince minutos, calendario integrado, con quien quieras ver representado. Recorremos el sistema y anotamos cada corrección sobre la marcha.' },
  'site.how_adapt': { en: 'Adapt', es: 'Adaptación' },
  'site.how_adapt_body': { en: 'What you actually read, opened and skipped changes what we show next and what we build next. The system keeps learning after go-live; that is the sixth step that never ends.', es: 'Lo que realmente lees, abres y saltas cambia lo que mostramos y lo que construimos después. El sistema sigue aprendiendo tras la puesta en marcha; ese es el sexto paso que no termina.' },
  'site.how_diagram_h2': { en: 'The engine', es: 'El motor' },
  'site.how_diagram_sub': { en: 'Every step is a pure function over what we know about you, so the same input always produces the same system.', es: 'Cada paso es una función pura sobre lo que sabemos de ti, así que la misma entrada produce siempre el mismo sistema.' },
  'site.how_diagram_title': { en: 'From intake to adaptation', es: 'Del intake a la adaptación' },
  'site.how_diagram_desc': { en: 'Six boxes in a row: intake, stack guess, compose, demo, book, adapt. An arrow loops from adapt back to compose.', es: 'Seis cajas en fila: intake, estimación del stack, composición, demo, reserva y adaptación. Una flecha vuelve desde adaptación a composición.' },
  'site.how_diagram_loop': { en: 'what you do on the page recomposes it', es: 'lo que haces en la página la recompone' },
  'site.faq_h2': { en: 'Questions people ask', es: 'Preguntas frecuentes' },
  'site.faq_real_q': { en: 'Is the demo real or a mockup?', es: '¿La demo es real o una maqueta?' },
  'site.faq_real_a': { en: 'Real. It runs in your browser with sample data, every role opens, every screen resizes from a phone to the TV in the back office. Payments, e-signature and live accounts arrive when you start; those are marked in the product wherever they are not wired yet.', es: 'Real. Funciona en tu navegador con datos de ejemplo, cada rol abre, cada pantalla se adapta del teléfono a la pantalla de la oficina. Los pagos, la firma electrónica y las cuentas reales llegan al empezar; lo que aún no está conectado está marcado dentro del producto.' },
  'site.faq_data_q': { en: 'Where does the data come from?', es: '¿De dónde salen los datos?' },
  'site.faq_data_a': { en: 'Public information plus whatever you tell us. Nothing in a demo is a real customer record, and we never load your live data before you decide to start.', es: 'Información pública más lo que nos cuentes. Nada en una demo es un registro real de cliente, y nunca cargamos tus datos reales antes de que decidas empezar.' },
  'site.faq_wrong_q': { en: 'What if your guesses are wrong?', es: '¿Y si se equivocan?' },
  'site.faq_wrong_a': { en: 'Then you correct them in the page and the numbers change in front of you. A wrong guess you can fix is more useful than a blank form.', es: 'Los corriges en la página y los números cambian delante de ti. Una estimación que puedes corregir vale más que un formulario en blanco.' },
  'site.faq_switch_q': { en: 'How long does switching take?', es: '¿Cuánto tarda el cambio?' },
  'site.faq_switch_a': { en: 'Phases are bound by dependencies, not calendar promises: intake, compose, demo, walkthrough, build passes, go-live. Each one starts when the one before it is accepted, and you see every pass as it lands.', es: 'Las fases dependen unas de otras, no de promesas de calendario: intake, composición, demo, recorrido, pases de construcción y salida a producción. Cada una empieza al aceptar la anterior, y ves cada pase al entregarse.' },
  'site.faq_lang_q': { en: 'Does it work in Spanish?', es: '¿Funciona en español?' },
  'site.faq_lang_a': { en: 'Yes. Every screen carries both languages and each person picks their own; the toggle is in the corner of this page too.', es: 'Sí. Cada pantalla lleva los dos idiomas y cada persona elige el suyo; el selector también está en la esquina de esta página.' },
  'site.faq_own_q': { en: 'Do we own it?', es: '¿Es nuestro?' },
  'site.faq_own_a': { en: 'Your data is yours and exportable from the first day. The system is licensed per month with no per-seat surprise; the band is set by your team size and your locations.', es: 'Tus datos son tuyos y exportables desde el primer día. El sistema se licencia por mes sin sorpresas por usuario; la banda depende de tu equipo y tus sedes.' },
  'site.notwired_h2': { en: 'What is not wired yet', es: 'Lo que aún no está conectado' },
  'site.devmode_only': { en: 'dev mode only', es: 'solo modo dev' },
  'site.notwired_sub': { en: 'Visible to the team while dev mode is on. Every one of these is a marked placeholder in the product, never a fake.', es: 'Visible para el equipo con el modo dev activo. Cada uno es un placeholder marcado en el producto, nunca una simulación.' },
  'site.notwired_images': { en: 'Image and video generation (prompts exist, provider does not)', es: 'Generación de imagen y vídeo (los prompts existen, el proveedor no)' },
  'site.notwired_llm': { en: 'LLM enrichment of a prospect from their website and socials', es: 'Enriquecimiento con LLM desde el sitio y las redes del prospecto' },
  'site.notwired_booking': { en: 'Real calendar provider behind the booking page', es: 'Proveedor de calendario real detrás de la página de reserva' },
  'site.notwired_stripe': { en: 'Stripe checkout, subscriptions and payroll', es: 'Checkout, suscripciones y nómina con Stripe' },
  'site.notwired_supabase': { en: 'Supabase database and real authentication', es: 'Base de datos Supabase y autenticación real' },
  'site.notwired_esign': { en: 'E-signature acceptance on the proposal', es: 'Aceptación con firma electrónica en la propuesta' },
  // W-03
  'site.pricing_eyebrow': { en: 'Pricing', es: 'Precios' },
  'site.pricing_h1': { en: 'One bill instead of nine.', es: 'Una factura en vez de nueve.' },
  'site.pricing_lede': { en: 'Bands are set by your team size and your locations, not by seats. Work out what you spend today with the calculator below - it runs the same engine we use to price a real system.', es: 'Las bandas dependen de tu equipo y tus sedes, no de usuarios. Calcula lo que gastas hoy con la calculadora - usa el mismo motor con el que cotizamos un sistema real.' },
  'site.pricing_proposed': { en: 'Dev mode: D-014 price bands are proposed ($249 / $499 / $899) until Justin sets pricing.', es: 'Modo dev: las bandas D-014 son propuestas ($249 / $499 / $899) hasta que Justin fije el precio.' },
  'site.incl_os': { en: 'The whole system, not a module', es: 'Todo el sistema, no un módulo' },
  'site.incl_roles': { en: 'A view for every business and life role', es: 'Una vista para cada rol del negocio y de la vida' },
  'site.incl_langs': { en: 'English and Spanish everywhere', es: 'Inglés y español en todo' },
  'site.incl_devices': { en: 'Phone to the back-office screen', es: 'Del teléfono a la pantalla de la oficina' },
  'site.incl_passes': { en: 'Repeated build passes and the ops manual', es: 'Pases de construcción repetidos y el manual de operaciones' },
  'site.choose_plan': { en: 'Choose plan', es: 'Elegir plan' },
  'site.calc_h2': { en: 'What are you paying today?', es: '¿Cuánto pagas hoy?' },
  'site.calc_sub': { en: 'Pick your industry and your size; we guess the stack the way we would guess yours, then show what is left after our plan.', es: 'Elige tu industria y tu tamaño; estimamos el stack como estimaríamos el tuyo y mostramos qué queda después de nuestro plan.' },
  'site.calc_industry': { en: 'Industry', es: 'Industria' },
  'site.calc_team': { en: 'Team size', es: 'Tamaño del equipo' },
  'site.calc_team_hint': { en: 'Everyone who would have a login', es: 'Todos los que tendrían acceso' },
  'site.calc_locations': { en: 'Locations', es: 'Sedes' },
  'site.calc_current': { en: 'Software today', es: 'Software hoy' },
  'site.calc_tools': { en: 'Tools we would replace', es: 'Herramientas que reemplazamos' },
  'site.calc_tools_hint': { en: 'one system instead', es: 'un sistema en su lugar' },
  'site.calc_ours': { en: 'Your band', es: 'Tu banda' },
  'site.calc_net': { en: 'Net saving', es: 'Ahorro neto' },
  'site.calc_note': { en: 'Estimates from typical prices in your industry, scaled by seats and locations. On a real prospect you correct every line before we quote.', es: 'Estimaciones con precios típicos de tu industria, ajustadas por usuarios y sedes. Con un prospecto real, cada línea se corrige antes de cotizar.' },
  'site.calc_caption': { en: 'Tools we would expect you to be paying for', es: 'Herramientas que esperaríamos que pagues' },
  'site.calc_empty': { en: 'No tools guessed for that combination', es: 'Sin herramientas estimadas para esa combinación' },
  'site.col_tool': { en: 'Tool', es: 'Herramienta' },
  'site.col_category': { en: 'Category', es: 'Categoría' },
  'site.col_replaced': { en: 'Replaced by', es: 'Reemplazado por' },
  'site.col_cost': { en: '$ / month', es: '$ / mes' },
  'site.checkout_h2': { en: 'Start', es: 'Empezar' },
  'site.checkout_selected': { en: 'selected', es: 'seleccionado' },
  'site.checkout_body': { en: 'Next: we confirm the details of your business, build your system and send you the link. Payment starts when you accept the proposal, not before.', es: 'Después: confirmamos los datos de tu negocio, construimos tu sistema y te mandamos el enlace. El pago empieza cuando aceptas la propuesta, no antes.' },
  'site.checkout_pay': { en: 'Continue to payment', es: 'Continuar al pago' },
  'site.checkout_talk': { en: 'Talk to us first', es: 'Hablar primero' },
  'site.checkout_recorded': { en: 'Your choice is recorded so we can pick up where you left off.', es: 'Guardamos tu elección para retomar donde lo dejaste.' },
  'site.checkout_empty': { en: 'Choose a band above and it appears here with what happens next.', es: 'Elige una banda arriba y aparecerá aquí con los siguientes pasos.' },
  'site.checkout_pick': { en: 'Use the {band} band', es: 'Usar la banda {band}' },
};
