import type { Rule } from './index';
export const rules: Rule[] = [
  { id: 'R-C01', title: 'The demo is never gated', description: 'No form before the demo. Ask for name / email at the moment of value ("save your workspace").', category: 'conversion', status: 'implemented', pages: ['L-01', 'L-02', 'L-03', 'L-04', 'C-01'], source: 'conversion-playbook 1', implementedIn: 'src/engine/compose.ts cta' },
  { id: 'R-C02', title: 'One primary CTA, one secondary', description: 'Primary "Open your demo" repeated; secondary "Book a 15-min walkthrough" with the calendar inline, never a link-out.', category: 'conversion', status: 'implemented', pages: ['L-01', 'L-02', 'L-03', 'L-04'], source: 'conversion-playbook 2', implementedIn: 'PageModel.cta' },
  { id: 'R-C03', title: 'Savings shown with a concrete number', description: 'The guessed stack with prices crossed out and the annual savings counting up; the prospect can correct the list.', category: 'conversion', status: 'implemented', pages: ['L-01', 'L-02'], source: 'conversion-playbook 3', implementedIn: 'src/engine/stack.ts' },
  { id: 'R-C04', title: 'Personalization above the fold', description: 'Name, business, palette, city and real roles are visible before any scroll.', category: 'conversion', status: 'implemented', pages: ['L-01', 'L-02', 'L-03', 'L-04'], source: 'conversion-playbook 4', implementedIn: 'hero_reveal section' },
  { id: 'R-C05', title: 'Honest urgency: 14-day workspace', description: 'Pages expire 14 days after publish; the CTA band says so. Expired pages render L-05.', category: 'conversion', status: 'in_dev', pages: ['L-01', 'L-05'], source: 'conversion-playbook 8, D-013 (proposed)' },
  { id: 'R-C06', title: 'Track every section', description: 'view, section_view, scroll_depth, cta_click, demo_open, demo_role_switch, booking_* through track().', category: 'tracking', status: 'implemented', pages: ['L-01', 'L-02', 'L-03', 'L-04', 'C-01', 'B-01'], source: 'conversion-playbook 9', implementedIn: 'src/tracking' },
  { id: 'R-E01', title: 'Stack guess picks one product per category', description: 'Highest prevalence per category unless a competitor is confirmed; low-prevalence tools only for teams >= 15; per-seat costs use half the team (min 2).', category: 'engine', status: 'implemented', pages: ['S-02', 'S-03', 'L-02'], source: 'engine', implementedIn: 'guessStack()' },
  { id: 'R-E02', title: 'Archetype scoring', description: 'cold: A3 B4; warm: A4 C3; hot: D4 A3; low revenue or >= 7 tools: +2 B; team >= 15 or >= 8 roles: +1 C; confidence < .4: +1 B.', category: 'engine', status: 'implemented', pages: ['S-03'], source: 'conversion-playbook', implementedIn: 'pickArchetype()' },
  { id: 'R-E03', title: 'Confidence is the weighted share of known fields', description: 'FIELD_WEIGHTS in intake.ts; nextQuestions() asks the heaviest unknown first.', category: 'engine', status: 'implemented', pages: ['S-02'], source: 'engine', implementedIn: 'computeConfidence()' },
  { id: 'R-P01', title: 'Roles never compared in pages', description: 'Pages call can(permission); permissions map per role in src/auth/permissions.ts.', category: 'platform', status: 'implemented', pages: ['HUB-01'], source: 'house pattern', implementedIn: 'SessionProvider.can' },
  { id: 'R-P02', title: 'Every unfinished control is a Placeholder', description: 'Tooltip on hover and focus, toast on activation, dashed outline + badge in dev mode, data-placeholder attribute.', category: 'platform', status: 'implemented', pages: ['HUB-01'], source: 'P-09', implementedIn: 'Placeholder atom' },
  { id: 'R-P03', title: 'Actions manifest is complete', description: 'Every button / submit on a page is an ActionDef in its spec; the manifest is the WebMCP surface and voice vocabulary.', category: 'platform', status: 'implemented', pages: ['D-04'], source: 'P-05', implementedIn: 'src/actions' },
];
