/**
 * Landing-module rules. The conversion principles themselves are R-C01..R-C06 in `core.ts` (shared with the engine and
 * the studio); these are the rules the L- pages add on top of them, and how a reviewer can check each one.
 */
import type { Rule } from './index';

export const rules: Rule[] = [
  { id: 'R-L01', title: 'The page renders the snapshot, not a fresh computation', description: 'A landing page reads pages.model and renders its sections in order. It only recomposes when the archetype in the URL differs from the snapshot (all four variants are reachable for every slug), and then with the same inputs: composePage(prospect, archetype, { pageId, slug, guesses, expiresAt }).', category: 'conversion', status: 'implemented', pages: ['L-01', 'L-02', 'L-03', 'L-04'], source: 'CLAUDE.md engine contract', implementedIn: 'src/modules/landing/usePageModel.ts' },
  { id: 'R-L02', title: 'Motion is optional, never load-bearing', description: 'Scroll reveals, the device parallax, the struck-through prices, the count-ups and the pinned story all live inside `prefers-reduced-motion: no-preference`. With reduced motion every section is visible and every number final on first paint, and the story still moves with its prev / next buttons.', category: 'accessibility', status: 'implemented', pages: ['L-01', 'L-02', 'L-03', 'L-04'], source: 'P-03, conversion-playbook 6', implementedIn: 'src/modules/landing/hooks.ts + landing.css' },
  { id: 'R-L03', title: 'Nothing is swipe-only or hover-only', description: 'The role carousel and the scroll story are reachable with arrow keys, Home / End and visible prev / next buttons; every hover state is also a focus state; every target is at least 44 px.', category: 'accessibility', status: 'implemented', pages: ['L-01', 'L-02', 'L-03'], source: 'P-03', implementedIn: 'RoleViews.tsx, WalkthroughSteps.tsx' },
  { id: 'R-L04', title: 'The page owns its chrome and its theme', description: 'No app shell on a public landing page: a slim bar with the prospect\'s business name as the wordmark, the language toggle and the primary CTA. prospectStyle() sets --lp-* on the page root and every section reads them; no token is redefined per prospect.', category: 'design', status: 'implemented', pages: ['L-01', 'L-02', 'L-03', 'L-04', 'L-05'], source: 'P-02, shells.tsx', implementedIn: 'src/modules/landing/LandingPage.tsx' },
  { id: 'R-L05', title: 'Placeholders where nothing is wired', description: 'Case studies, the letter\'s voice note and booking without a workspace link are Placeholders, and the testimonial / logo strip is labelled a sample. We never fabricate proof, audio or availability.', category: 'honesty', status: 'implemented', pages: ['L-01', 'L-02', 'L-04', 'L-05'], source: 'P-09', implementedIn: 'Proof.tsx, Letter.tsx, ExpiredPage.tsx' },
  { id: 'R-L06', title: 'Corrections are writes, not local state', description: 'Every Yes / No in the stack audit updates stack_guesses.status by id through the DataProvider and emits a form_submit event, so the savings number, the studio and the analytics all read the same corrected rows (P-14).', category: 'data', status: 'implemented', pages: ['L-02'], source: 'conversion-playbook 3', implementedIn: 'src/modules/landing/sections/StackAudit.tsx' },
];
