import type { Rule } from './index';

/** R-S01: a page below this confidence needs an explicit override before it can go live. */
export const MIN_PUBLISH_CONFIDENCE = 0.3;
/** R-S02: honest urgency - a published workspace lives 14 days (D-013, proposed). */
export const PAGE_TTL_DAYS = 14;
export const expiresAtFrom = (published: Date = new Date()): string => new Date(published.getTime() + PAGE_TTL_DAYS * 86400000).toISOString();

export const rules: Rule[] = [
  { id: 'R-S01', title: 'Publishing needs 30 % confidence or an explicit override', description: 'A page composed from a profile we barely know is worse than no page: publish is blocked under confidence 0.3 unless the strategist turns the override on, and the override is recorded in the toast and the page doc.', category: 'studio', status: 'implemented', pages: ['S-03', 'S-02'], source: 'conversion-playbook 4 + P-09 honesty', implementedIn: 'src/modules/studio/ComposePage.tsx publish()' },
  { id: 'R-S02', title: 'Pages expire 14 days after publish', description: 'publish sets published_at = now and expires_at = now + 14 days; expire sets status expired and keeps the PageModel snapshot so the page doc and analytics still resolve. Matches R-C05 on the landing side (D-013, proposed).', category: 'studio', status: 'implemented', pages: ['S-03', 'S-01', 'L-01', 'L-05'], source: 'conversion-playbook 8, D-013 (proposed)', implementedIn: 'src/rules/studio.ts PAGE_TTL_DAYS' },
  { id: 'R-S04', title: 'A slug carries at most two live pages: variant A and variant B', description: 'The A/B test is two live `pages` rows on one slug, each with its own archetype and its own PageModel snapshot. S-03 publishes and expires them one at a time and hands out `#/p/<slug>?variant=B` to force a side; the landing module splits sessions between the live rows and honours the query. Anything that needs "the" page (S-01, S-02, outreach) takes variant A.', category: 'studio', status: 'implemented', pages: ['S-03', 'S-01', 'L-01', 'A-01'], source: 'conversion-playbook 10 (test one thing at a time)', implementedIn: 'src/modules/studio/ComposePage.tsx publish(), src/modules/studio/lib.ts variantRows()' },
  { id: 'R-S05', title: 'Pasted facts are proposed, never applied', description: 'The paste-facts extractor reads city, team size, locations, catalog tool names, language and website out of pasted copy and shows each one with the words that produced it. A person presses Apply before anything is written; dismissing leaves the profile untouched. The extractor is pure rules - no LLM, no network (T43 keeps the LLM path a Placeholder).', category: 'studio', status: 'implemented', pages: ['S-02'], source: 'P-09 honesty + D-017', implementedIn: 'src/modules/studio/extract.ts, src/modules/studio/IntakeChat.tsx' },
  { id: 'R-S06', title: 'Every intake answer is recorded as a transcript turn', description: 'Each answer appends an `intake_turns` row: the field, the question exactly as it was asked, the answer as it was saved, the source (manual, rule, llm) and the confidence right after. The transcript is how we can tell a profile the strategist confirmed from one a rule filled in - and it survives a reload.', category: 'studio', status: 'implemented', pages: ['S-02', 'A-01'], source: 'P-09 honesty, org docs-same-turn rule', implementedIn: 'src/modules/studio/ProspectProfilePage.tsx recordTurn()' },
  { id: 'R-S07', title: 'Duplicating a prospect copies the profile, never the page', description: 'Duplicate as new prospect copies the person, business, roles, style, known tools and fields_known under a new name and re-guesses the stack. Pages, events, bookings, touches and assets stay with the original, so a demo copy can never show another prospect\u2019s traffic as its own.', category: 'studio', status: 'implemented', pages: ['S-01'], source: 'fast demo setup', implementedIn: 'src/modules/studio/ProspectsPage.tsx duplicate()' },
  { id: 'R-S03', title: 'Every studio write goes through update by id', description: 'No in-memory-only edits: intake answers, tool confirmations, roles, style, asset status and touches all write through useData().update(table, id, patch) (or insert), so a realtime provider swaps in without touching a page (P-14, P-15).', category: 'studio', status: 'implemented', pages: ['S-01', 'S-02', 'S-03', 'S-04', 'S-05'], source: 'house pattern, P-14', implementedIn: 'src/modules/studio/*' },
];
