import { createElement as h } from 'react';
import type { RouteDef } from '../../specs/types';
import { EVERYONE } from '../../auth/roles';
import { ProposalPage } from './ProposalPage';
import { proposalSpec } from './specs';

export const routes: RouteDef[] = [
  { path: '/proposal/:prospectId', element: h(ProposalPage), spec: proposalSpec, roles: EVERYONE, surface: 'public' },
];

/** EN + ES. Headlines and CTAs are written in both; the long descriptive bodies are EN-only and flagged for the Spanish pass (T30). */
export const strings = {
  'proposal.locale': { en: 'en-US', es: 'es-ES' },
  'proposal.missing': { en: 'We could not find that proposal', es: 'No encontramos esa propuesta' },
  'proposal.missing_body': { en: 'The link may be old, or the prospect was removed from the demo data. Open the hub and pick a prospect.', es: 'El enlace puede estar vencido o el prospecto ya no está en los datos demo. Abre el hub y elige un prospecto.' },
  'proposal.back_hub': { en: 'Back to the hub', es: 'Volver al hub' },
  'proposal.print': { en: 'Print', es: 'Imprimir' },
  'proposal.eyebrow': { en: 'Proposal', es: 'Propuesta' },
  'proposal.cover_h1': { en: 'An operating system for {business}, already built.', es: 'Un sistema operativo para {business}, ya construido.' },
  'proposal.cover_lede': { en: 'This proposal covers the system you already saw: {business} in {city}, themed to your brand, with a view for every role in the business and in your life, on phone, laptop and the screen in the back office. Everything in it is running today as {industry} software, not a mockup.', es: 'Esta propuesta cubre el sistema que ya viste: {business} en {city}, con tu marca, con una vista para cada rol del negocio y de tu vida, en teléfono, portátil y la pantalla de la oficina. Todo funciona hoy, no es una maqueta.' },
  'proposal.prepared_for': { en: 'Prepared for', es: 'Preparado para' },
  'proposal.prepared_by': { en: 'Prepared by', es: 'Preparado por' },
  'proposal.date': { en: 'Date', es: 'Fecha' },
  'proposal.band': { en: 'Plan', es: 'Plan' },
  'proposal.band_starter': { en: 'Starter (one location, up to 5 people)', es: 'Starter (una sede, hasta 5 personas)' },
  'proposal.band_team': { en: 'Team (one location, up to 25 people)', es: 'Team (una sede, hasta 25 personas)' },
  'proposal.band_multi': { en: 'Multi (several locations or 25+ people)', es: 'Multi (varias sedes o más de 25 personas)' },
  'proposal.get_h2': { en: 'What you get', es: 'Qué recibes' },
  'proposal.get_sub': { en: 'One system replaces the tools {business} pays for today. Every surface below is part of the same product, with the same data, the same roles and the same brand.', es: 'Un sistema reemplaza las herramientas que {business} paga hoy. Cada superficie es parte del mismo producto, con los mismos datos, roles y marca.' },
  'proposal.device_phone': { en: '{business} on a phone', es: '{business} en el teléfono' },
  'proposal.device_laptop': { en: '{business} on a laptop', es: '{business} en el portátil' },
  'proposal.device_tv': { en: '{business} on the back-office screen', es: '{business} en la pantalla de la oficina' },
  'proposal.surface_website': { en: 'Public website', es: 'Sitio público' },
  'proposal.surface_website_body': { en: 'Your public pages and the way new customers find and buy from {business}.', es: 'Tus páginas públicas y la forma en que los clientes encuentran y compran en {business}.' },
  'proposal.surface_app': { en: 'Customer app', es: 'App de clientes' },
  'proposal.surface_app_body': { en: 'Booking, messages, documents and payments for the people {business} serves.', es: 'Reservas, mensajes, documentos y pagos para los clientes de {business}.' },
  'proposal.surface_staff': { en: 'Staff and admin dashboards', es: 'Paneles de equipo y administración' },
  'proposal.surface_staff_body': { en: 'A home screen per role: the day, the numbers that matter and what needs a decision.', es: 'Una pantalla por rol: el día, los números que importan y lo que necesita una decisión.' },
  'proposal.surface_docs': { en: 'Documentation', es: 'Documentación' },
  'proposal.surface_docs_body': { en: 'How the system works, written down and searchable, in English and Spanish.', es: 'Cómo funciona el sistema, escrito y buscable, en inglés y español.' },
  'proposal.surface_manual': { en: 'Operations manual', es: 'Manual de operaciones' },
  'proposal.surface_manual_body': { en: 'How {business} runs: the procedures a new hire follows on day one.', es: 'Cómo opera {business}: los procedimientos que sigue alguien nuevo el primer día.' },
  'proposal.surface_devtools': { en: 'Developer tools', es: 'Herramientas de desarrollo' },
  'proposal.surface_devtools_body': { en: 'Every page, table, action and rule listed in the product, so changes are cheap and visible.', es: 'Cada página, tabla, acción y regla listada en el producto, para que los cambios sean baratos y visibles.' },
  'proposal.surface_testing': { en: 'Testing hub', es: 'Hub de pruebas' },
  'proposal.surface_testing_body': { en: 'View the whole system as any role, on any device size, before anyone else sees it.', es: 'Ve todo el sistema como cualquier rol y en cualquier tamaño de pantalla, antes que nadie.' },
  'proposal.savings_h2': { en: 'What it replaces', es: 'Qué reemplaza' },
  'proposal.savings_sub': { en: 'Our estimate of what {business} pays for today, {tools} tools that do not talk to each other. Correct any line and the numbers move with it.', es: 'Nuestra estimación de lo que {business} paga hoy: {tools} herramientas que no se hablan entre sí. Corrige cualquier línea y los números se ajustan.' },
  'proposal.stat_today': { en: 'Software today', es: 'Software hoy' },
  'proposal.stat_tools': { en: 'Tools cut', es: 'Herramientas eliminadas' },
  'proposal.stat_tools_hint': { en: 'replaced by one system', es: 'reemplazadas por un sistema' },
  'proposal.stat_ours': { en: 'Your plan', es: 'Tu plan' },
  'proposal.stat_net': { en: 'Net saving', es: 'Ahorro neto' },
  'proposal.per_month': { en: 'per month', es: 'al mes' },
  'proposal.per_year': { en: 'per year', es: 'al año' },
  'proposal.table_caption': { en: 'Software {business} pays for today and what replaces it', es: 'Software que {business} paga hoy y qué lo reemplaza' },
  'proposal.col_tool': { en: 'Tool', es: 'Herramienta' },
  'proposal.col_category': { en: 'Category', es: 'Categoría' },
  'proposal.col_replaced': { en: 'Replaced by', es: 'Reemplazado por' },
  'proposal.col_cost': { en: '$ / month', es: '$ / mes' },
  'proposal.confirmed': { en: 'confirmed', es: 'confirmado' },
  'proposal.savings_note': { en: 'That is {annual} a year on software, before the hours spent moving data between it. Net of our plan you keep {net} every month.', es: 'Son {annual} al año en software, sin contar las horas moviendo datos entre herramientas. Descontando nuestro plan, te quedas con {net} cada mes.' },
  'proposal.roles_h2': { en: 'Who gets a view', es: 'Quién recibe una vista' },
  'proposal.roles_sub': { en: 'Every role in the business, and every role in your life. Each one opens on what that person needs first.', es: 'Cada rol del negocio y cada rol de tu vida. Cada uno abre en lo que esa persona necesita primero.' },
  'proposal.role_business': { en: 'business', es: 'negocio' },
  'proposal.role_life': { en: 'life', es: 'vida' },
  'proposal.role_line': { en: 'Opens on: {widgets}', es: 'Abre en: {widgets}' },
  'proposal.timeline_h2': { en: 'How it runs', es: 'Cómo avanza' },
  'proposal.timeline_sub': { en: 'Phases are bound by dependencies, not calendar days: each one starts when the one before it is accepted.', es: 'Las fases dependen unas de otras, no del calendario: cada una empieza cuando se acepta la anterior.' },
  'proposal.phase_intake': { en: 'Intake', es: 'Intake' },
  'proposal.phase_intake_body': { en: 'We confirm what we know about {business}: people, roles, locations, the tools you actually pay for.', es: 'Confirmamos lo que sabemos de {business}: personas, roles, sedes y las herramientas que realmente pagas.' },
  'proposal.phase_compose': { en: 'Compose', es: 'Composición' },
  'proposal.phase_compose_body': { en: 'We compose your system: brand, departments, role views, documents and the data model behind them.', es: 'Componemos tu sistema: marca, departamentos, vistas por rol, documentos y el modelo de datos detrás.' },
  'proposal.phase_demo': { en: 'Demo', es: 'Demo' },
  'proposal.phase_demo_body': { en: 'You open the live system yourself, on your phone and on a big screen, and switch between roles.', es: 'Abres el sistema en vivo, en tu teléfono y en pantalla grande, y cambias de rol.' },
  'proposal.phase_walkthrough': { en: 'Walkthrough', es: 'Recorrido' },
  'proposal.phase_walkthrough_body': { en: 'Fifteen minutes together: we walk the system with the people who will use it and write down every correction.', es: 'Quince minutos juntos: recorremos el sistema con quienes lo usarán y anotamos cada corrección.' },
  'proposal.phase_passes': { en: 'Build passes', es: 'Pases de construcción' },
  'proposal.phase_passes_body': { en: 'Repeated passes: real data, real accounts, payments, the Spanish pass, polish. You see each pass as it lands.', es: 'Pases repetidos: datos reales, cuentas reales, pagos, el pase en español, pulido. Ves cada pase al entregarse.' },
  'proposal.phase_golive': { en: 'Go live', es: 'Salida a producción' },
  'proposal.phase_golive_body': { en: 'Your team moves in, the old tools are cancelled one by one, and the saving starts.', es: 'Tu equipo se muda, las herramientas viejas se cancelan una por una y empieza el ahorro.' },
  'proposal.phase_dep_none': { en: 'Starts on acceptance', es: 'Empieza al aceptar' },
  'proposal.phase_dep': { en: 'Depends on: {prev}', es: 'Depende de: {prev}' },
  'proposal.price_h2': { en: 'Price', es: 'Precio' },
  'proposal.price_why': { en: 'Based on {team} people and {locations} location(s).', es: 'Según {team} personas y {locations} sede(s).' },
  'proposal.month': { en: 'month', es: 'mes' },
  'proposal.incl_os': { en: 'The whole system: website, customer app, staff and admin dashboards', es: 'Todo el sistema: sitio, app de clientes, paneles de equipo y administración' },
  'proposal.incl_roles': { en: 'A view for every business and life role, with real permissions', es: 'Una vista para cada rol del negocio y de la vida, con permisos reales' },
  'proposal.incl_brand': { en: 'Your brand throughout: palette, type, imagery, documents', es: 'Tu marca en todo: paleta, tipografía, imágenes, documentos' },
  'proposal.incl_langs': { en: 'English and Spanish across every screen', es: 'Inglés y español en cada pantalla' },
  'proposal.incl_devices': { en: 'Phone, tablet, laptop and the big screen in the back office', es: 'Teléfono, tablet, portátil y la pantalla grande de la oficina' },
  'proposal.incl_support': { en: 'Documentation, the operations manual and repeated build passes', es: 'Documentación, manual de operaciones y pases de construcción repetidos' },
  'proposal.price_compare': { en: 'Against {current} a month in software today, that is {net} back every month.', es: 'Frente a {current} al mes en software hoy, son {net} de vuelta cada mes.' },
  'proposal.price_proposed': { en: 'Dev mode: price bands are D-014 (proposed) - $249 / $499 / $899 until Justin sets pricing.', es: 'Modo dev: las bandas de precio son D-014 (propuesto) - $249 / $499 / $899 hasta que Justin fije el precio.' },
  'proposal.next_h2': { en: 'Next steps', es: 'Siguientes pasos' },
  'proposal.next_sub': { en: 'Nothing here needs a signature to keep looking. The demo stays open.', es: 'Nada aquí necesita firma para seguir mirando. La demo sigue abierta.' },
  'proposal.next_1': { en: 'Book the 15-minute walkthrough at a time that suits you.', es: 'Reserva el recorrido de 15 minutos a la hora que te sirva.' },
  'proposal.next_2': { en: 'Bring anyone whose role you want to see: manager, front desk, accountant.', es: 'Trae a quien quieras ver representado: gerente, recepción, contador.' },
  'proposal.next_3': { en: 'Accept the proposal and we start the intake pass the same week.', es: 'Acepta la propuesta y empezamos el intake la misma semana.' },
  'proposal.book': { en: 'Book the walkthrough', es: 'Reservar el recorrido' },
  'proposal.accept': { en: 'Accept proposal', es: 'Aceptar propuesta' },
  'proposal.open_demo': { en: 'Open the live demo', es: 'Abrir la demo en vivo' },
  'proposal.signature': { en: 'Imagine', es: 'Imagine' },
  'proposal.foot': { en: 'Proposal for {business} - {date} - prepared by Imagine', es: 'Propuesta para {business} - {date} - preparada por Imagine' },
};
