import { defineSpec, type PageSpec } from '../../specs/types';
import type { Role } from '../../auth/roles';
export const DEV_ROLES: Role[] = ['super_admin'];
export const DOCS_ROLES: Role[] = ['super_admin', 'strategist', 'analyst'];
const base = { roles: DEV_ROLES, integrations: [] as string[], states: ['default', 'empty'], checkedAt: [390, 1280] };
export const specs: Record<string, PageSpec> = {
  routes: defineSpec({ ...base, code: 'D-01', name: 'Routes manifest', purpose: 'Every route with code, surface, status, roles, spec completeness and action count; the same manifest window.__leadmagnet exposes.', layout: ['counts', 'filter by surface / status', 'DataTable'], data: [], logic: ['status = built | stub from registry', 'completeness from specCompleteness()'], components: ['DataTable', 'Chip', 'Stat', 'Badge', 'ProgressBar'], actions: [{ id: 'dev.filterRoutes', label: 'Filter', intent: 'show {surface} routes', params: { surface: 'string' } }] }),
  components: defineSpec({ ...base, code: 'D-02', name: 'Component library', purpose: 'Every component meta with props, states, a11y and live usages, grouped by tier.', layout: ['tier tabs', 'component cards with live usages'], data: [], logic: ['globbed from src/components/**/*.meta.ts'], components: ['Tabs', 'Card', 'Badge'], actions: [{ id: 'dev.pickTier', label: 'Tier', intent: 'show {tier} components', params: { tier: 'enum:atom|molecule|organism|template' } }] }),
  tables: defineSpec({ ...base, code: 'D-03', name: 'Tables', purpose: 'Browse any table: schema columns and seeded rows, live via useTable.', layout: ['table list with counts', 'columns', 'rows'], data: ['prospects', 'stack_guesses', 'pages', 'events', 'bookings', 'assets', 'touches', 'tasks', 'feedback'], logic: ['reads schema registry + DataProvider'], components: ['DataTable', 'Badge', 'Chip'], actions: [{ id: 'dev.openTable', label: 'Open table', intent: 'open the {table} table', params: { table: 'string' }, permission: 'tables.read' }, { id: 'dev.resetDb', label: 'Reset demo data', intent: 'reset the demo database', permission: 'dev.tools' }] }),
  actions: defineSpec({ ...base, code: 'D-04', name: 'Actions registry', purpose: 'Every declared action with page, permission, params and handler-live status. This manifest is the WebMCP surface and the voice vocabulary (P-05).', layout: ['counts', 'DataTable', 'run panel'], data: [], logic: ['flattens spec.actions across routes', 'live = registered on the actions bus (open the page first)'], components: ['DataTable', 'Badge', 'Button', 'Stat'], actions: [{ id: 'dev.runAction', label: 'Run', intent: 'run action {id}', params: { id: 'string' }, permission: 'dev.tools' }] }),
  rules: defineSpec({ ...base, code: 'D-05', name: 'Rules', purpose: 'Business rules registry (R-xxx) with status, pages and where implemented.', layout: ['filter', 'rules list'], data: [], logic: ['globbed from src/rules/*.ts'], components: ['Card', 'Badge', 'Chip'], actions: [{ id: 'dev.filterRules', label: 'Filter', intent: 'show {status} rules', params: { status: 'string' } }] }),
  docs: defineSpec({ ...base, roles: DOCS_ROLES, code: 'D-06', name: 'Docs viewer', purpose: 'Every docs/**/*.md rendered in-app with tabs for kanban, changelog, prompts, decisions, pages, reference.', layout: ['tabs', 'file list', 'markdown'], data: [], logic: ['import.meta.glob docs/**/*.md as raw'], components: ['Tabs', 'Card'], actions: [{ id: 'dev.openDoc', label: 'Open doc', intent: 'open the {doc} document', params: { doc: 'string' }, permission: 'docs.read' }] }),
  canvas: defineSpec({ ...base, code: 'D-07', name: 'Page canvas', purpose: 'Zoomable, pannable canvas laying out every route as a card grouped by surface: code chip, status colour, live scaled iframe thumbnail on demand; click opens the page.', layout: ['toolbar (zoom -, %, +, fit, thumbnails, surface filter)', 'canvas (groups by surface, cards)', 'legend / help'], data: [], logic: ['zoom: buttons, +/- keys, wheel; pan: arrow keys, drag, scrollbars (drag never the only way)', 'thumbnails are same-origin iframes at 1280 scaled to the card'], components: ['Button', 'IconButton', 'Chip', 'Badge', 'Tooltip', 'Card'], actions: [{ id: 'dev.canvasZoomIn', label: 'Zoom in', intent: 'zoom in the canvas' }, { id: 'dev.canvasZoomOut', label: 'Zoom out', intent: 'zoom out the canvas' }, { id: 'dev.canvasFit', label: 'Fit', intent: 'fit the canvas' }, { id: 'dev.canvasThumbnails', label: 'Thumbnails', intent: 'toggle live thumbnails' }, { id: 'dev.canvasOpen', label: 'Open page', intent: 'open page {code}', params: { code: 'string' } }], states: ['default', 'thumbnails on', 'filtered'] }),
  qa: defineSpec({ ...base, code: 'D-08', name: 'QA preview', purpose: 'Any route side by side at 360 / 390 / 768 / 1280 / 1920 / 2560 / 3840 in same-origin iframes scaled to fit.', layout: ['route picker', 'width chips', 'frames'], data: [], logic: ['ViewportFrame scales with ResizeObserver'], components: ['ViewportFrame', 'Select', 'Chip'], actions: [{ id: 'dev.previewRoute', label: 'Preview', intent: 'preview {route} at every width', params: { route: 'string' } }] }),
  feedback: defineSpec({ ...base, roles: ['super_admin', 'strategist'], code: 'D-09', name: 'Feedback inbox', purpose: 'Annotations triage: every feedback row; set triage (fix / ask / later / wontfix), status and decision_ref before changing anything (P-08).', layout: ['status tabs', 'DataTable', 'row editor'], data: ['feedback'], logic: ['writes by id through the provider'], components: ['Tabs', 'DataTable', 'Select', 'Input', 'Button', 'Badge', 'EmptyState'], actions: [{ id: 'dev.triageFeedback', label: 'Triage', intent: 'triage feedback {id} as {triage}', params: { id: 'id', triage: 'enum:fix|ask|later|wontfix' }, permission: 'feedback.read' }, { id: 'dev.setFeedbackStatus', label: 'Set status', intent: 'mark feedback {id} {status}', params: { id: 'id', status: 'enum:new|seen|waiting|done' }, permission: 'feedback.read' }] }),
};
