import { createElement as h } from 'react';
import type { RouteDef } from '../../specs/types';
import { STUDIO_ROLES, specs } from './specs';
import { ProspectsPage } from './ProspectsPage';
import { ProspectProfilePage } from './ProspectProfilePage';
import { ComposePage } from './ComposePage';
import { AssetsPage } from './AssetsPage';
import { OutreachPage } from './OutreachPage';

export const routes: RouteDef[] = [
  { path: '/studio', element: h(ProspectsPage), spec: specs.list, roles: STUDIO_ROLES, surface: 'studio', nav: { label: 'Prospects', icon: 'users', order: 1, group: 'studio' } },
  { path: '/studio/prospects/:id', element: h(ProspectProfilePage), spec: specs.profile, roles: STUDIO_ROLES, surface: 'studio' },
  { path: '/studio/prospects/:id/compose', element: h(ComposePage), spec: specs.compose, roles: STUDIO_ROLES, surface: 'studio' },
  { path: '/studio/prospects/:id/assets', element: h(AssetsPage), spec: specs.assets, roles: STUDIO_ROLES, surface: 'studio' },
  { path: '/studio/prospects/:id/outreach', element: h(OutreachPage), spec: specs.outreach, roles: STUDIO_ROLES, surface: 'studio' },
];

export const strings = {
  // shell / nav
  'studio.nav_label': { en: 'Prospect sections', es: 'Secciones del prospecto' },
  'studio.all_prospects': { en: 'All prospects', es: 'Todos los prospectos' },
  'studio.tab_profile': { en: 'Profile & intake', es: 'Perfil e intake' },
  'studio.tab_compose': { en: 'Compose', es: 'Componer' },
  'studio.tab_assets': { en: 'Assets', es: 'Assets' },
  'studio.tab_outreach': { en: 'Outreach', es: 'Outreach' },
  'studio.not_found': { en: 'No prospect with that id', es: 'No hay prospecto con ese id' },
  'studio.not_found_body': { en: 'It may have been removed, or the demo data was reset.', es: 'Puede que se haya borrado o que se reiniciaran los datos demo.' },
  'studio.not_wired': { en: 'Not wired yet', es: 'Aún no conectado' },
  'studio.save': { en: 'Save', es: 'Guardar' },
  'studio.cancel': { en: 'Cancel', es: 'Cancelar' },
  'studio.add': { en: 'Add', es: 'Añadir' },
  'studio.all': { en: 'All', es: 'Todos' },
  'studio.choose': { en: 'Choose…', es: 'Elegir…' },
  'studio.confirm': { en: 'Confirm', es: 'Confirmar' },
  'studio.reject': { en: 'Reject', es: 'Descartar' },
  'studio.approve': { en: 'Approve', es: 'Aprobar' },
  'studio.preview': { en: 'Preview', es: 'Vista previa' },
  'studio.comma_separated': { en: 'Comma separated', es: 'Separado por comas' },

  // S-01
  'studio.s01_title': { en: 'Prospects', es: 'Prospectos' },
  'studio.s01_sub': { en: 'Who we are building for, how much we know, and whether their workspace is live.', es: 'Para quién construimos, cuánto sabemos y si su espacio está en vivo.' },
  'studio.new_prospect': { en: 'New prospect', es: 'Nuevo prospecto' },
  'studio.new_hint': { en: 'Six fields is enough to start: the industry catalog fills the roles, the engine guesses the stack, and the intake asks for the rest.', es: 'Seis campos bastan: el catálogo de industrias llena los roles, el motor estima el stack y el intake pide el resto.' },
  'studio.new_needs_fields': { en: 'A first name and a business name are required', es: 'Se requiere nombre y nombre del negocio' },
  'studio.new_created': { en: '{business} created', es: '{business} creado' },
  'studio.new_created_body': { en: 'Stack guessed. Answer the intake questions to raise the confidence.', es: 'Stack estimado. Responde el intake para subir la confianza.' },
  'studio.create_and_intake': { en: 'Create and start intake', es: 'Crear e iniciar intake' },
  'studio.filters': { en: 'Filters', es: 'Filtros' },
  'studio.all_industries': { en: 'Every industry', es: 'Todas las industrias' },
  'studio.only_live': { en: 'Only with a live page', es: 'Solo con página en vivo' },
  'studio.showing': { en: 'Showing {n} of {total}', es: 'Mostrando {n} de {total}' },
  'studio.col_name': { en: 'Person', es: 'Persona' },
  'studio.col_business': { en: 'Business', es: 'Negocio' },
  'studio.col_industry': { en: 'Industry', es: 'Industria' },
  'studio.col_warmth': { en: 'Warmth', es: 'Temperatura' },
  'studio.col_confidence': { en: 'Confidence', es: 'Confianza' },
  'studio.col_page': { en: 'Live page', es: 'Página en vivo' },
  'studio.col_last_event': { en: 'Last event', es: 'Último evento' },
  'studio.col_booking': { en: 'Booking', es: 'Reserva' },
  'studio.no_page': { en: 'No page yet', es: 'Sin página' },
  'studio.no_booking': { en: 'None', es: 'Ninguna' },
  'studio.never': { en: 'Never', es: 'Nunca' },
  'studio.days_left': { en: '{n} days left', es: 'Quedan {n} días' },
  'studio.expired_ago': { en: 'Expired', es: 'Vencida' },
  'studio.empty_title': { en: 'No prospects match', es: 'Ningún prospecto coincide' },
  'studio.empty_body': { en: 'Clear the filters, or create the first prospect.', es: 'Quita los filtros o crea el primer prospecto.' },
  'studio.kpi_prospects': { en: 'Prospects', es: 'Prospectos' },
  'studio.kpi_live': { en: 'Live pages', es: 'Páginas en vivo' },
  'studio.kpi_live_hint': { en: '14-day workspaces', es: 'Espacios de 14 días' },
  'studio.kpi_confidence': { en: 'Avg confidence', es: 'Confianza media' },
  'studio.kpi_bookings': { en: 'Bookings', es: 'Reservas' },
  'studio.f_first_name': { en: 'First name', es: 'Nombre' },
  'studio.f_last_name': { en: 'Last name', es: 'Apellido' },
  'studio.f_business': { en: 'Business name', es: 'Nombre del negocio' },
  'studio.f_business_hint': { en: 'As it appears on their sign', es: 'Como aparece en su letrero' },
  'studio.f_industry': { en: 'Industry', es: 'Industria' },
  'studio.f_industry_hint': { en: 'Sets the roles, the stack guess and the motifs', es: 'Define roles, estimación de stack y motivos' },
  'studio.f_city': { en: 'City', es: 'Ciudad' },
  'studio.f_lang': { en: 'Language', es: 'Idioma' },
  'studio.f_warmth': { en: 'Warmth', es: 'Temperatura' },
  'studio.f_source': { en: 'Source', es: 'Origen' },
  'studio.f_team_size': { en: 'Team size', es: 'Tamaño del equipo' },
  'studio.f_team_size_hint': { en: 'People, including the owner', es: 'Personas, incluyendo al dueño' },
  'studio.f_tone': { en: 'Tone', es: 'Tono' },
  'studio.f_font': { en: 'Font', es: 'Tipografía' },

  // S-02
  'studio.s02_title': { en: 'Profile', es: 'Perfil' },
  'studio.palette': { en: 'Palette', es: 'Paleta' },
  'studio.team': { en: 'Team', es: 'Equipo' },
  'studio.locations_n': { en: '{n} location(s)', es: '{n} sede(s)' },
  'studio.confidence': { en: 'Confidence', es: 'Confianza' },
  'studio.net_savings': { en: 'Net savings / yr', es: 'Ahorro neto / año' },
  'studio.tools_cut_n': { en: '{n} tools cut', es: '{n} herramientas fuera' },
  'studio.recommended': { en: 'Recommended page', es: 'Página recomendada' },
  'studio.score_n': { en: 'score {n}', es: 'puntaje {n}' },
  'studio.open_composer': { en: 'Open the composer', es: 'Abrir el compositor' },
  'studio.intake': { en: 'AI intake', es: 'Intake con IA' },
  'studio.intake_sub': { en: 'The heaviest unknown first. Every answer raises the confidence and can change the recommended archetype.', es: 'Primero lo desconocido de mayor peso. Cada respuesta sube la confianza y puede cambiar el arquetipo recomendado.' },
  'studio.intake_done': { en: 'Nothing left to ask', es: 'No queda nada por preguntar' },
  'studio.intake_done_body': { en: 'Every weighted field is known. Compose the page.', es: 'Todos los campos ponderados son conocidos. Compón la página.' },
  'studio.weight_hint': { en: 'weight {w} · {field}', es: 'peso {w} · {field}' },
  'studio.answer_empty': { en: 'Nothing to save', es: 'Nada que guardar' },
  'studio.answer_saved': { en: '{field} saved', es: '{field} guardado' },
  'studio.confidence_now': { en: 'Confidence is now {pct}', es: 'La confianza ahora es {pct}' },
  'studio.mark_style_known': { en: 'Mark style as known', es: 'Marcar estilo como conocido' },
  'studio.style_below': { en: 'Edit it in the style card', es: 'Edítalo en la tarjeta de estilo' },
  'studio.known': { en: 'What we know', es: 'Lo que sabemos' },
  'studio.unknown': { en: 'Still unknown', es: 'Aún desconocido' },
  'studio.nothing_unknown': { en: 'Nothing - the profile is complete.', es: 'Nada: el perfil está completo.' },
  'studio.stack': { en: 'Stack guesses', es: 'Stack estimado' },
  'studio.stack_sub': { en: 'Confirm what they really pay for and reject what they do not; the savings follow.', es: 'Confirma lo que realmente pagan y descarta lo demás; el ahorro se recalcula.' },
  'studio.no_guesses': { en: 'No stack guesses', es: 'Sin estimaciones de stack' },
  'studio.no_guesses_body': { en: 'Set the industry and the intake will generate them.', es: 'Define la industria y el intake las generará.' },
  'studio.replaced_by': { en: 'replaced by {by}', es: 'reemplaza {by}' },
  'studio.savings_month': { en: '{v} / month net', es: '{v} / mes neto' },
  'studio.pays_today': { en: 'Pays today', es: 'Paga hoy' },
  'studio.per_month': { en: 'per month', es: 'al mes' },
  'studio.per_year': { en: 'per year', es: 'al año' },
  'studio.our_price': { en: 'Our price', es: 'Nuestro precio' },
  'studio.net_month': { en: 'Net / month', es: 'Neto / mes' },
  'studio.net_year': { en: 'Net / year', es: 'Neto / año' },
  'studio.roles': { en: 'Roles', es: 'Roles' },
  'studio.roles_sub': { en: 'Every role becomes a view in their OS demo and a card on the page.', es: 'Cada rol se convierte en una vista de su demo y una tarjeta en la página.' },
  'studio.roles_business': { en: 'Business roles', es: 'Roles del negocio' },
  'studio.roles_life': { en: 'Life roles', es: 'Roles de su vida' },
  'studio.add_role_business': { en: 'Add a business role', es: 'Añadir rol del negocio' },
  'studio.add_role_life': { en: 'Add a life role', es: 'Añadir rol de su vida' },
  'studio.remove_role': { en: 'Remove {role}', es: 'Quitar {role}' },
  'studio.style': { en: 'Style', es: 'Estilo' },
  'studio.style_sub': { en: 'Their colours drive the --lp-* custom properties on every prospect page; the platform tokens never fork.', es: 'Sus colores alimentan las propiedades --lp-* de cada página; los tokens de la plataforma no se bifurcan.' },
  'studio.preview_head': { en: 'We already built {business}.', es: 'Ya construimos {business}.' },
  'studio.preview_cta': { en: 'Open your demo', es: 'Abrir tu demo' },
  'studio.enrichment': { en: 'Enrichment', es: 'Enriquecimiento' },
  'studio.enrichment_sub': { en: 'The rule enricher fills what the industry catalog already implies. The LLM enricher lands in T43.', es: 'El enriquecedor de reglas llena lo que el catálogo ya implica. El enriquecedor LLM llega en T43.' },
  'studio.enrich_ai': { en: 'Enrich with AI', es: 'Enriquecer con IA' },
  'studio.enrich_llm_will': { en: 'call the LLM enricher and fill the profile from the web', es: 'llamar al enriquecedor LLM y llenar el perfil desde la web' },
  'studio.fill_gaps': { en: 'Fill obvious gaps', es: 'Llenar lo obvio' },
  'studio.enrich_done': { en: '{n} field(s) filled', es: '{n} campo(s) llenados' },
  'studio.enrich_nothing': { en: 'Nothing obvious left', es: 'No queda nada obvio' },
  'studio.enrich_nothing_body': { en: 'The rule enricher only fills roles the industry catalog implies.', es: 'El enriquecedor de reglas solo llena roles implícitos en el catálogo.' },
  'studio.notes': { en: 'Research notes', es: 'Notas de investigación' },
  'studio.notes_hint': { en: 'Where we met them, what their site says, who referred them.', es: 'Dónde los conocimos, qué dice su sitio, quién los refirió.' },
  'studio.save_notes': { en: 'Save notes', es: 'Guardar notas' },
  'studio.notes_saved': { en: 'Notes saved', es: 'Notas guardadas' },

  // S-03
  'studio.s03_title': { en: 'Compose the page', es: 'Componer la página' },
  'studio.s03_sub': { en: 'Pick the archetype, check it at phone and desktop width, then publish a workspace that lives {days} days.', es: 'Elige el arquetipo, revísalo en teléfono y escritorio, y publica un espacio que dura {days} días.' },
  'studio.ranking': { en: 'Archetype ranking', es: 'Ranking de arquetipos' },
  'studio.ranking_sub': { en: 'pickArchetype() scores warmth, revenue band, team size, roles and confidence (R-E02).', es: 'pickArchetype() puntúa temperatura, ingresos, tamaño, roles y confianza (R-E02).' },
  'studio.top': { en: 'Top', es: 'Mejor' },
  'studio.score': { en: 'Score', es: 'Puntaje' },
  'studio.no_reasons': { en: 'no signals yet', es: 'aún sin señales' },
  'studio.use_this': { en: 'Use this', es: 'Usar este' },
  'studio.archetype': { en: 'Archetype', es: 'Arquetipo' },
  'studio.variant': { en: 'Variant', es: 'Variante' },
  'studio.variant_hint': { en: 'A / B label for the funnel', es: 'Etiqueta A / B para el embudo' },
  'studio.variant_n': { en: 'variant {v}', es: 'variante {v}' },
  'studio.slug': { en: 'Slug', es: 'Slug' },
  'studio.slug_hint': { en: 'Never moves once published', es: 'No cambia una vez publicada' },
  'studio.tools': { en: 'Tools replaced', es: 'Herramientas reemplazadas' },
  'studio.preview_note': { en: 'The real public route in a same-origin frame.', es: 'La ruta pública real en un marco del mismo origen.' },
  'studio.phone_390': { en: 'Phone · 390', es: 'Teléfono · 390' },
  'studio.desktop_1280': { en: 'Desktop · 1280', es: 'Escritorio · 1280' },
  'studio.publish': { en: 'Publish', es: 'Publicar' },
  'studio.publish_14': { en: 'Publish for {days} days', es: 'Publicar por {days} días' },
  'studio.republish': { en: 'Republish', es: 'Republicar' },
  'studio.published': { en: 'Page published', es: 'Página publicada' },
  'studio.published_body': { en: '{slug} is live for {days} days', es: '{slug} está en vivo {days} días' },
  'studio.expire': { en: 'Expire now', es: 'Vencer ahora' },
  'studio.expired': { en: 'Page expired', es: 'Página vencida' },
  'studio.expired_body': { en: 'The public route now shows the expired page (L-05).', es: 'La ruta pública ahora muestra la página vencida (L-05).' },
  'studio.copy_link': { en: 'Copy link', es: 'Copiar enlace' },
  'studio.copied': { en: 'Link copied', es: 'Enlace copiado' },
  'studio.copy_failed': { en: 'Copy it by hand', es: 'Cópialo a mano' },
  'studio.open_public': { en: 'Open the public page', es: 'Abrir la página pública' },
  'studio.public_link': { en: 'Public link', es: 'Enlace público' },
  'studio.gate_title': { en: 'Too little known to publish', es: 'Sabemos muy poco para publicar' },
  'studio.gate_body': { en: 'R-S01: publishing needs {pct} confidence, or an explicit override.', es: 'R-S01: publicar requiere {pct} de confianza o una anulación explícita.' },
  'studio.gate_hint': { en: 'gate at {pct}', es: 'límite en {pct}' },
  'studio.override': { en: 'Publish anyway', es: 'Publicar de todos modos' },
  'studio.override_desc': { en: 'I know the profile is thin and I want the page live.', es: 'Sé que el perfil es pobre y aun así quiero la página en vivo.' },

  // S-04
  'studio.s04_title': { en: 'Assets & image prompts', es: 'Assets y prompts de imagen' },
  'studio.s04_sub': { en: 'Every prompt the page needs, with the palette and the motifs baked in. Edit before generating.', es: 'Cada prompt que necesita la página, con la paleta y los motivos incluidos. Edítalos antes de generar.' },
  'studio.provider_not_wired': { en: 'Image provider not wired (T40)', es: 'Proveedor de imágenes sin conectar (T40)' },
  'studio.asset_total': { en: 'Prompts', es: 'Prompts' },
  'studio.no_assets': { en: 'No assets yet', es: 'Aún sin assets' },
  'studio.no_assets_body': { en: 'They are created from imagePrompts() the first time this page opens.', es: 'Se crean desde imagePrompts() la primera vez que se abre esta página.' },
  'studio.prompt': { en: 'Prompt', es: 'Prompt' },
  'studio.prompt_saved': { en: 'Prompt saved', es: 'Prompt guardado' },
  'studio.generate': { en: 'Generate', es: 'Generar' },
  'studio.generate_will': { en: 'send the {kind} prompt to the image provider', es: 'enviar el prompt de {kind} al proveedor de imágenes' },

  // S-05
  'studio.s05_title': { en: 'Outreach', es: 'Outreach' },
  'studio.s05_sub': { en: 'Two or three templates per channel, filled from the profile and the savings, pointing at the page.', es: 'Dos o tres plantillas por canal, llenas con el perfil y el ahorro, apuntando a la página.' },
  'studio.no_page_yet': { en: 'No live page: publish one first', es: 'Sin página en vivo: publica una primero' },
  'studio.channel': { en: 'Channel', es: 'Canal' },
  'studio.message_lang': { en: 'Message language', es: 'Idioma del mensaje' },
  'studio.tokens_hint': { en: 'Tokens: {first_name} {business} {savings_annual} {tools_cut} {page_url}', es: 'Tokens: {first_name} {business} {savings_annual} {tools_cut} {page_url}' },
  'studio.templates': { en: 'Templates', es: 'Plantillas' },
  'studio.use_template': { en: 'Use', es: 'Usar' },
  'studio.in_use': { en: 'In use', es: 'En uso' },
  'studio.message': { en: 'Message', es: 'Mensaje' },
  'studio.subject_hint': { en: 'Subject line, DM opener or call reason', es: 'Asunto, apertura del DM o motivo de la llamada' },
  'studio.body': { en: 'Body', es: 'Cuerpo' },
  'studio.body_hint': { en: 'Tokens are already filled; edit freely.', es: 'Los tokens ya están llenos; edita libremente.' },
  'studio.draft': { en: 'Draft', es: 'Guardar borrador' },
  'studio.drafted': { en: 'Draft saved to touches', es: 'Borrador guardado en touches' },
  'studio.send': { en: 'Send', es: 'Enviar' },
  'studio.send_will': { en: 'send this message through the channel provider', es: 'enviar este mensaje por el proveedor del canal' },
  'studio.reset_template': { en: 'Reset to template', es: 'Volver a la plantilla' },
  'studio.mark_sent': { en: 'Mark as sent', es: 'Marcar enviado' },
  'studio.marked_sent': { en: 'Marked as sent', es: 'Marcado como enviado' },
  'studio.marked_sent_body': { en: 'Demo only: nothing left the building.', es: 'Solo demo: nada salió de aquí.' },
  'studio.page_url': { en: 'Page URL', es: 'URL de la página' },
  'studio.history': { en: 'Touch history', es: 'Historial de contactos' },
  'studio.no_touches': { en: 'No touches yet', es: 'Aún sin contactos' },
  'studio.no_touches_body': { en: 'Draft one above and it lands here.', es: 'Guarda un borrador arriba y aparecerá aquí.' },
  'studio.col_channel': { en: 'Channel', es: 'Canal' },
  'studio.col_subject': { en: 'Subject', es: 'Asunto' },
  'studio.col_status': { en: 'Status', es: 'Estado' },
  'studio.col_sent': { en: 'Sent', es: 'Enviado' },
  'studio.col_opened': { en: 'Opened', es: 'Abierto' },
  'studio.col_act': { en: 'Action', es: 'Acción' },

  // enums
  'studio.warmth_cold': { en: 'Cold', es: 'Frío' }, 'studio.warmth_warm': { en: 'Warm', es: 'Tibio' }, 'studio.warmth_hot': { en: 'Hot', es: 'Caliente' },
  'studio.arch_reveal': { en: 'A · Reveal', es: 'A · Revelación' }, 'studio.arch_audit': { en: 'B · Savings audit', es: 'B · Auditoría de ahorro' }, 'studio.arch_walkthrough': { en: 'C · Walkthrough', es: 'C · Recorrido' }, 'studio.arch_letter': { en: 'D · Letter', es: 'D · Carta' },
  'studio.status_live': { en: 'Live', es: 'En vivo' }, 'studio.status_draft': { en: 'Draft', es: 'Borrador' }, 'studio.status_expired': { en: 'Expired', es: 'Vencida' },
  'studio.status_queued': { en: 'Queued', es: 'En cola' }, 'studio.status_generated': { en: 'Generated', es: 'Generado' }, 'studio.status_approved': { en: 'Approved', es: 'Aprobado' }, 'studio.status_rejected': { en: 'Rejected', es: 'Descartado' },
  'studio.booking_requested': { en: 'Requested', es: 'Solicitada' }, 'studio.booking_confirmed': { en: 'Confirmed', es: 'Confirmada' }, 'studio.booking_cancelled': { en: 'Cancelled', es: 'Cancelada' }, 'studio.booking_completed': { en: 'Completed', es: 'Completada' },
  'studio.source_cold_email': { en: 'Cold email', es: 'Correo en frío' }, 'studio.source_linkedin': { en: 'LinkedIn', es: 'LinkedIn' }, 'studio.source_referral': { en: 'Referral', es: 'Referido' }, 'studio.source_event': { en: 'Event', es: 'Evento' }, 'studio.source_inbound': { en: 'Inbound', es: 'Entrante' },
  'studio.channel_cold_email': { en: 'Cold email', es: 'Correo en frío' }, 'studio.channel_linkedin_dm': { en: 'LinkedIn DM', es: 'DM de LinkedIn' }, 'studio.channel_whatsapp': { en: 'WhatsApp', es: 'WhatsApp' }, 'studio.channel_sms': { en: 'SMS', es: 'SMS' }, 'studio.channel_call': { en: 'Call', es: 'Llamada' }, 'studio.channel_warm_intro': { en: 'Warm intro', es: 'Presentación' },
  'studio.touch_draft': { en: 'Draft', es: 'Borrador' }, 'studio.touch_scheduled': { en: 'Scheduled', es: 'Programado' }, 'studio.touch_sent': { en: 'Sent', es: 'Enviado' }, 'studio.touch_opened': { en: 'Opened', es: 'Abierto' }, 'studio.touch_clicked': { en: 'Clicked', es: 'Con clic' }, 'studio.touch_replied': { en: 'Replied', es: 'Respondido' }, 'studio.touch_bounced': { en: 'Bounced', es: 'Rebotado' },
  'studio.guess_guessed': { en: 'Guessed', es: 'Estimado' }, 'studio.guess_confirmed': { en: 'Confirmed', es: 'Confirmado' }, 'studio.guess_rejected': { en: 'Rejected', es: 'Descartado' },
  'studio.tone_bold': { en: 'Bold', es: 'Audaz' }, 'studio.tone_warm': { en: 'Warm', es: 'Cálido' }, 'studio.tone_clean': { en: 'Clean', es: 'Limpio' }, 'studio.tone_luxury': { en: 'Luxury', es: 'Lujo' }, 'studio.tone_playful': { en: 'Playful', es: 'Juguetón' },
  'studio.font_display': { en: 'Display', es: 'Display' }, 'studio.font_humanist': { en: 'Humanist', es: 'Humanista' }, 'studio.font_serif': { en: 'Serif', es: 'Serif' }, 'studio.font_mono': { en: 'Mono', es: 'Mono' },
  'studio.band_lt250k': { en: 'Under $250k', es: 'Menos de $250k' }, 'studio.band_250k_1m': { en: '$250k - $1M', es: '$250k - $1M' }, 'studio.band_1m_5m': { en: '$1M - $5M', es: '$1M - $5M' }, 'studio.band_5m_plus': { en: '$5M+', es: '$5M+' },
  'studio.band_price_starter': { en: 'starter band', es: 'banda inicial' }, 'studio.band_price_team': { en: 'team band', es: 'banda equipo' }, 'studio.band_price_multi': { en: 'multi-location band', es: 'banda multi-sede' },
  'studio.pal_primary': { en: 'Primary', es: 'Primario' }, 'studio.pal_accent': { en: 'Accent', es: 'Acento' }, 'studio.pal_bg': { en: 'Background', es: 'Fondo' }, 'studio.pal_surface': { en: 'Surface', es: 'Superficie' }, 'studio.pal_text': { en: 'Text', es: 'Texto' },
  'studio.asset_hero': { en: 'Hero', es: 'Hero' }, 'studio.asset_device_phone': { en: 'Phone mockup', es: 'Mockup de teléfono' }, 'studio.asset_device_laptop': { en: 'Laptop mockup', es: 'Mockup de laptop' }, 'studio.asset_device_tv': { en: 'TV mockup', es: 'Mockup de TV' }, 'studio.asset_role_card': { en: 'Role cards', es: 'Tarjetas de rol' }, 'studio.asset_og_image': { en: 'Social preview', es: 'Vista previa social' }, 'studio.asset_video_frames': { en: 'Video frames', es: 'Cuadros de video' },

  // intake field labels (FIELD_WEIGHTS keys)
  'studio.field_industry': { en: 'Industry', es: 'Industria' }, 'studio.field_business_name': { en: 'Business name', es: 'Nombre del negocio' }, 'studio.field_first_name': { en: 'First name', es: 'Nombre' },
  'studio.field_team_size': { en: 'Team size', es: 'Tamaño del equipo' }, 'studio.field_known_tools': { en: 'Known tools', es: 'Herramientas conocidas' }, 'studio.field_locations': { en: 'Locations', es: 'Sedes' },
  'studio.field_business_roles': { en: 'Business roles', es: 'Roles del negocio' }, 'studio.field_life_roles': { en: 'Life roles', es: 'Roles de su vida' }, 'studio.field_style': { en: 'Brand style', es: 'Estilo de marca' },
  'studio.field_warmth': { en: 'Warmth', es: 'Temperatura' }, 'studio.field_revenue_band': { en: 'Revenue band', es: 'Rango de ingresos' }, 'studio.field_city': { en: 'City', es: 'Ciudad' },
  'studio.field_lang': { en: 'Language', es: 'Idioma' }, 'studio.field_website': { en: 'Website', es: 'Sitio web' }, 'studio.field_photo_url': { en: 'Photo', es: 'Foto' },

  // shared verbs added by the 0.3.0 studio pass
  'studio.skip': { en: 'Skip', es: 'Saltar' },
  'studio.unskip': { en: 'Bring the skipped questions back', es: 'Recuperar las preguntas saltadas' },
  'studio.apply': { en: 'Apply', es: 'Aplicar' },
  'studio.dismiss': { en: 'Dismiss', es: 'Descartar' },
  'studio.clear': { en: 'Clear', es: 'Limpiar' },
  'studio.proposed': { en: 'Proposed', es: 'Propuesto' },
  'studio.duplicate': { en: 'Duplicate', es: 'Duplicar' },
  'studio.duplicate_name': { en: 'Duplicate {name} as a new prospect', es: 'Duplicar {name} como nuevo prospecto' },

  // S-01 summary strip + duplicate
  'studio.summary': { en: 'What to look at next', es: 'Qué mirar ahora' },
  'studio.summary_sub': { en: 'The strategist strip: who is warm, what is live, who is coming and what expires first.', es: 'La franja del estratega: quién está tibio, qué está en vivo, quién viene y qué vence primero.' },
  'studio.by_warmth': { en: '{cold} cold · {warm} warm · {hot} hot', es: '{cold} frío · {warm} tibio · {hot} caliente' },
  'studio.kpi_split_hint': { en: '{n} slug(s) running an A/B split', es: '{n} slug(s) con prueba A/B' },
  'studio.kpi_bookings_week': { en: 'Bookings this week', es: 'Reservas esta semana' },
  'studio.kpi_bookings_all': { en: '{n} in total', es: '{n} en total' },
  'studio.kpi_next_expiring': { en: 'Next page expiring', es: 'Próxima página que vence' },
  'studio.kpi_none_expiring': { en: 'Nothing live; pages last {days} days', es: 'Nada en vivo; las páginas duran {days} días' },
  'studio.open_expiring': { en: 'Open {slug} in the composer', es: 'Abrir {slug} en el compositor' },
  'studio.copy_of': { en: '{name} (copy)', es: '{name} (copia)' },
  'studio.duplicated': { en: '{business} duplicated', es: '{business} duplicado' },
  'studio.duplicated_body': { en: 'Profile, roles and style copied; the page, events and bookings stayed with the original (R-S07).', es: 'Perfil, roles y estilo copiados; la página, los eventos y las reservas quedaron con el original (R-S07).' },

  // S-02 conversational intake
  'studio.transcript': { en: 'Intake transcript', es: 'Transcripción del intake' },
  'studio.transcript_empty': { en: 'Nothing asked yet. The first question is below.', es: 'Aún no se ha preguntado nada. La primera pregunta está abajo.' },
  'studio.asking_n': { en: '{n} question(s) left', es: 'Quedan {n} pregunta(s)' },
  'studio.why_matters': { en: 'Why it matters: {why}', es: 'Por qué importa: {why}' },
  'studio.gain_hint': { en: 'Answering adds about {pts} confidence points (weight {w}).', es: 'Responder suma unos {pts} puntos de confianza (peso {w}).' },
  'studio.suggestions': { en: 'Suggestions from the industry catalog', es: 'Sugerencias del catálogo de industrias' },
  'studio.ask_ai': { en: 'Ask the AI', es: 'Preguntar a la IA' },
  'studio.ask_llm': { en: 'Research it for me', es: 'Investígalo por mí' },
  'studio.intake_skipped': { en: '{n} question(s) skipped; bring them back whenever you learn the answer.', es: '{n} pregunta(s) saltadas; recupéralas cuando sepas la respuesta.' },
  'studio.paste_facts': { en: 'Paste facts', es: 'Pegar datos' },
  'studio.paste_hint': { en: 'Website copy, a job post, call notes. We read it with rules and propose answers - nothing is saved until you press Apply.', es: 'Texto del sitio, una vacante, notas de llamada. Lo leemos con reglas y proponemos respuestas: nada se guarda hasta que pulses Aplicar.' },
  'studio.paste_placeholder': { en: 'Paste what they wrote about themselves…', es: 'Pega lo que escribieron sobre sí mismos…' },
  'studio.extract': { en: 'Read it', es: 'Leerlo' },
  'studio.facts_found': { en: '{n} fact(s) proposed', es: '{n} dato(s) propuestos' },
  'studio.facts_none': { en: 'Nothing we recognise in that text', es: 'No reconocemos nada en ese texto' },
  'studio.facts_confirm_note': { en: 'Proposals only: you confirm each one.', es: 'Solo propuestas: tú confirmas cada una.' },
  'studio.facts_question': { en: 'From pasted text: {field}?', es: 'Del texto pegado: ¿{field}?' },
  'studio.src_manual': { en: 'Strategist', es: 'Estratega' },
  'studio.src_rule': { en: 'Rules', es: 'Reglas' },
  'studio.src_llm': { en: 'LLM', es: 'LLM' },
  'studio.tier_likely': { en: 'Likely', es: 'Probable' },
  'studio.tier_possible': { en: 'Possible', es: 'Posible' },

  // what each intake field changes (shown with the question)
  'studio.effect_industry': { en: 'it sets the whole catalog: roles, tool stack, KPIs and the imagery', es: 'define todo el catálogo: roles, herramientas, KPIs e imágenes' },
  'studio.effect_business_name': { en: 'it is the headline, the slug and every device mockup', es: 'es el titular, el slug y cada mockup' },
  'studio.effect_first_name': { en: 'the letter archetype and every message open with it', es: 'la carta y cada mensaje abren con él' },
  'studio.effect_team_size': { en: 'it scales every per-seat price and the price band', es: 'escala cada precio por usuario y la banda de precio' },
  'studio.effect_known_tools': { en: 'a named tool is a confirmed savings line instead of a guess', es: 'una herramienta con nombre es un ahorro confirmado, no una estimación' },
  'studio.effect_locations': { en: 'it scales per-site prices and can push them to the multi band', es: 'escala precios por sede y puede llevarlos a la banda multi' },
  'studio.effect_business_roles': { en: 'each role becomes a view in the demo and a card on the page', es: 'cada rol es una vista en el demo y una tarjeta en la página' },
  'studio.effect_life_roles': { en: 'this is what makes it their life, not just their business', es: 'esto es lo que lo hace su vida, no solo su negocio' },
  'studio.effect_style': { en: 'their colours and tone theme every prospect surface', es: 'sus colores y tono tematizan cada superficie del prospecto' },
  'studio.effect_warmth': { en: 'it is the biggest input to the recommended archetype', es: 'es el mayor insumo del arquetipo recomendado' },
  'studio.effect_revenue_band': { en: 'a low band tilts the page towards the savings audit', es: 'una banda baja inclina la página hacia la auditoría de ahorro' },
  'studio.effect_city': { en: 'it sets the local proof and the booking timezone', es: 'define la prueba local y la zona horaria de la reserva' },
  'studio.effect_lang': { en: 'their page opens in this language', es: 'su página abre en este idioma' },
  'studio.effect_website': { en: 'the next pass pulls logo, palette and photos from it', es: 'el siguiente pase toma logo, paleta y fotos de ahí' },
  'studio.effect_photo_url': { en: 'a face makes the letter and the hero land', es: 'una cara hace que la carta y el hero funcionen' },

  // S-03 A/B variants
  'studio.variants': { en: 'Variants on this slug', es: 'Variantes de este slug' },
  'studio.variants_sub': { en: 'Two live pages on one link: sessions are split between them and ?variant= forces a side. Test one thing at a time.', es: 'Dos páginas en vivo en un enlace: las sesiones se reparten y ?variant= fuerza un lado. Prueba una sola cosa a la vez.' },
  'studio.live_variants_n': { en: '{n} live', es: '{n} en vivo' },
  'studio.split_running': { en: 'A/B split running', es: 'Prueba A/B activa' },
  'studio.no_variant_yet': { en: 'Variant {v} not published', es: 'Variante {v} sin publicar' },
  'studio.not_published': { en: 'Not published', es: 'Sin publicar' },
  'studio.published_at': { en: 'Published {when}', es: 'Publicada {when}' },
  'studio.open_variant': { en: 'Open variant {v}', es: 'Abrir variante {v}' },
  'studio.variant_a_hint': { en: 'The default side of the split: the link without a query lands here.', es: 'El lado por defecto: el enlace sin parámetros llega aquí.' },
  'studio.variant_b_hint': { en: 'The challenger. Same slug, same or different archetype - change one thing so the result means something.', es: 'El retador. Mismo slug, mismo u otro arquetipo: cambia una sola cosa para que el resultado signifique algo.' },
  'studio.publish_variant': { en: 'Publish variant {v}', es: 'Publicar variante {v}' },
  'studio.edit_variant': { en: 'Set up variant {v}', es: 'Preparar variante {v}' },
  'studio.same_archetype_warn': { en: 'Both live variants use the same archetype: the split will not tell you much until one of them changes.', es: 'Las dos variantes en vivo usan el mismo arquetipo: la prueba no dirá mucho hasta que una cambie.' },
  'studio.republish_variant': { en: 'Republish variant {v}', es: 'Republicar variante {v}' },
  'studio.publish_14_variant': { en: 'Publish variant {v} for {days} days', es: 'Publicar variante {v} por {days} días' },
  'studio.published_variant_body': { en: '{slug} variant {v} is live for {days} days', es: '{slug} variante {v} está en vivo {days} días' },
  'studio.expired_variant_body': { en: 'Variant {v} now shows the expired page (L-05).', es: 'La variante {v} ahora muestra la página vencida (L-05).' },

};
