import { defineSpec, type PageSpec } from '../../specs/types';
import type { Role } from '../../auth/roles';

/** Studio is the strategist's workbench: prospects -> intake -> compose -> assets -> outreach. */
export const STUDIO_ROLES: Role[] = ['super_admin', 'strategist'];
const base = { roles: STUDIO_ROLES, integrations: [] as string[], checkedAt: [360, 390, 768, 1280, 1920, 2560, 3840] };

export const specs = {
  list: defineSpec({
    ...base, code: 'S-01', name: 'Prospects list', tone: 'list',
    purpose: 'Every prospect with warmth, confidence, the live page (archetype, status, expiry), the last tracked event and the booking state, under a summary strip that says what to look at next; filter by warmth, industry and whether a page is live; create or duplicate a prospect and go straight into intake.',
    layout: ['page head + New prospect', 'strategist summary strip (warmth split, live pages, bookings this week, next expiring page)', 'filters (warmth chips, industry select, live-page toggle)', 'DataTable (cards under 768) with a duplicate action', 'new prospect Modal'],
    data: ['prospects (read/write)', 'pages (read)', 'events (read)', 'bookings (read)', 'stack_guesses (write on create)'],
    logic: [
      'live page per prospect = the row with status live, else the most recently published',
      'last event = max(ts) over events for that prospect',
      'booking = the latest bookings row by slot',
      'create: insert prospects with the industry catalog roles + the default palette, confidence = computeConfidence(fields_known, { industry }) (the same denominator S-02 uses: a sub-industry the catalog does not have is left out), then insert guessStack() rows, then navigate to S-02',
      'summary strip = studioSummary(prospects, pages, bookings): warmth split, live pages (and how many slugs run an A/B split), bookings within a week either side of now, the live page expiring first',
      'duplicate: copy the profile, roles, style and fields_known under a new name, re-guess the stack, and leave pages / events / bookings behind (R-S07)',
    ],
    components: ['DataTable', 'Chip', 'Select', 'Toggle', 'Button', 'Badge', 'ProgressBar', 'Stat', 'Modal', 'Field', 'Input', 'Card', 'EmptyState'],
    actions: [
      { id: 'studio.newProspect', label: 'New prospect', intent: 'create a prospect', permission: 'prospects.write' },
      { id: 'studio.createProspect', label: 'Create prospect', intent: 'create {business} in {industry}', params: { business: 'string', industry: 'string' }, permission: 'prospects.write' },
      { id: 'studio.filterProspects', label: 'Filter', intent: 'show {warmth} prospects in {industry}', params: { warmth: 'string', industry: 'string', live: 'string' } },
      { id: 'studio.openProspect', label: 'Open', intent: 'open prospect {name}', params: { name: 'string' } },
      { id: 'studio.duplicateProspect', label: 'Duplicate', intent: 'duplicate prospect {name} as a new prospect', params: { name: 'string' }, permission: 'prospects.write' },
    ],
    rules: ['R-S03', 'R-S07', 'R-E01', 'R-E03'], states: ['loading', 'default', 'filtered', 'empty', 'modal open'],
  }),
  profile: defineSpec({
    ...base, code: 'S-02', name: 'Prospect profile + AI intake', tone: 'form',
    purpose: 'Everything we know about one prospect and the conversational intake that closes the gaps: one question at a time with the reason it matters and what it would change, every answer kept as a transcript turn, applyAnswer() on save, confidence and the recommended archetype recomputing live, stack guesses to confirm or reject with the savings total, and a paste-facts box that proposes answers a person confirms.',
    layout: ['prospect nav', 'header (palette swatches, tone, warmth, language)', 'confidence meter + recommendation', 'intake chat (transcript, current question, suggestions, paste facts + proposals)', 'stack guesses + savings with likely / possible tiers', 'what we know / still unknown', 'roles editor', 'style editor + mini preview', 'enrichment'],
    data: ['prospects (read/write)', 'stack_guesses (read/write)', 'intake_turns (read/write)', 'pages (read)'],
    logic: [
      'nextQuestions(p, 12) is the queue; exactly one question is asked at a time, with the confidence points it would add and the sentence saying what it changes, and Skip moves to the next without losing it',
      'each field renders the control its type deserves (select for enums, number for counts, comma list for arrays) with one-tap suggestion chips from the industry catalog',
      'every answer appends an intake_turns row (field, question as asked, answer as saved, source manual | rule | llm, confidence after) - R-S06',
      'Ask the AI runs defaultEnricher (rules) and records source = rule; the LLM enricher stays a Placeholder (T43)',
      'Paste facts runs extractFacts() over pasted text (city, team size, locations, catalog tool names, language, website) and PROPOSES each one with its evidence; nothing is applied without a person pressing Apply (R-S05)',
      'save = applyAnswer(p, field, value) then update("prospects", id, { field, fields_known, confidence }) - R-S03',
      'confidence = computeConfidence(fields_known, prospect) (R-E03; fields that do not apply to the prospect leave the denominator); the recommendation is pickArchetype(p)[0] and re-ranks on every answer',
      'confirm / reject writes stack_guesses.status by id; savings(p, guesses) ignores rejected rows',
      'the mini preview uses prospectStyle(palette, font) -> --lp-* custom properties, never forked tokens',
      'defaultEnricher (rules) fills obvious gaps; the LLM enricher is not wired (T43)',
    ],
    components: ['ProgressBar', 'Field', 'Input', 'Select', 'Chip', 'Card', 'Badge', 'Button', 'Stat', 'Textarea', 'Placeholder', 'Avatar', 'EmptyState', 'Toast'],
    actions: [
      { id: 'studio.answerQuestion', label: 'Save answer', intent: 'answer {field} with {value}', params: { field: 'string', value: 'string' }, permission: 'prospects.write' },
      { id: 'studio.confirmTool', label: 'Confirm tool', intent: 'confirm {tool}', params: { tool: 'string' }, permission: 'prospects.write' },
      { id: 'studio.rejectTool', label: 'Reject tool', intent: 'reject {tool}', params: { tool: 'string' }, permission: 'prospects.write' },
      { id: 'studio.addRole', label: 'Add role', intent: 'add the {role} {kind} role', params: { role: 'string', kind: 'enum:business|life' }, permission: 'prospects.write' },
      { id: 'studio.removeRole', label: 'Remove role', intent: 'remove the {role} {kind} role', params: { role: 'string', kind: 'enum:business|life' }, permission: 'prospects.write' },
      { id: 'studio.setStyle', label: 'Set style', intent: 'set {key} to {value}', params: { key: 'string', value: 'string' }, permission: 'prospects.write' },
      { id: 'studio.saveNotes', label: 'Save notes', intent: 'save the research notes', permission: 'prospects.write' },
      { id: 'studio.fillGaps', label: 'Fill obvious gaps', intent: 'fill the obvious gaps with the rule enricher', permission: 'prospects.write' },
      { id: 'studio.runEnricher', label: 'Enrich with AI', intent: 'enrich this prospect', permission: 'prospects.write' },
      { id: 'studio.openCompose', label: 'Compose the page', intent: 'compose the page', permission: 'pages.publish' },
      { id: 'studio.skipQuestion', label: 'Skip', intent: 'skip this question and ask the next one' },
      { id: 'studio.pasteFacts', label: 'Paste facts', intent: 'paste {text} into the facts box', params: { text: 'string' }, permission: 'prospects.write' },
      { id: 'studio.extractFacts', label: 'Extract facts', intent: 'extract the facts from the pasted text', permission: 'prospects.write' },
      { id: 'studio.applyFact', label: 'Apply', intent: 'apply the proposed {fact}', params: { fact: 'string' }, permission: 'prospects.write' },
      { id: 'studio.dismissFact', label: 'Dismiss', intent: 'dismiss the proposed {fact}', params: { fact: 'string' } },
    ],
    rules: ['R-S03', 'R-S05', 'R-S06', 'R-E01', 'R-E03'], states: ['loading', 'asking', 'facts proposed', 'fully known', 'skipped questions', 'not found'],
  }),
  compose: defineSpec({
    ...base, code: 'S-03', name: 'Page composer', tone: 'form',
    purpose: 'Rank the four archetypes with their reasons, pick one, preview the real landing route at 390 and 1280, and publish up to two live variants of the same slug - A and B, same or different archetype - each with its own PageModel snapshot, forced link and expiry.',
    layout: ['prospect nav', 'live page status', 'variants A / B cards (archetype, published, expiry, forced link, copy, expire)', 'archetype ranking cards with score bars', 'segmented archetype + variant picker', 'previews (390 / 1280) of the selected variant', 'publish / expire'],
    data: ['prospects (read)', 'stack_guesses (read)', 'pages (read/write, one row per variant)'],
    logic: [
      'pickArchetype(p) gives score + reasons; the top score sets the card order',
      'the preview iframes the real public route for the archetype (/p/:slug, /p/:slug/audit, /p/:slug/story, /p/:slug/letter)',
      'publish writes pages: status live, published_at now, expires_at +14 days (R-S02), model = composePage() snapshot, slug from the existing row or slugify(business)',
      'a slug can carry two live rows, variant A and variant B, each with its own archetype and its own model snapshot; the landing module splits sessions between them and honours ?variant=A|B (R-S04)',
      'publishing variant X updates that variant\'s row if it exists and inserts one otherwise; expiry and copy-link are per variant',
      'publish is blocked under 0.3 confidence unless the override is on (R-S01)',
      'expire sets status expired and leaves the snapshot in place',
    ],
    components: ['ViewportFrame', 'SegmentedControl', 'Card', 'Button', 'Badge', 'ProgressBar', 'Field', 'Toggle', 'Stat', 'Chip'],
    actions: [
      { id: 'studio.pickArchetype', label: 'Use this archetype', intent: 'use the {archetype} archetype', params: { archetype: 'enum:reveal|audit|walkthrough|letter' }, permission: 'pages.publish' },
      { id: 'studio.setVariant', label: 'Variant', intent: 'set the variant to {variant}', params: { variant: 'string' }, permission: 'pages.publish' },
      { id: 'studio.overrideConfidence', label: 'Override the gate', intent: 'publish anyway under 30 % confidence', permission: 'pages.publish' },
      { id: 'studio.publishPage', label: 'Publish', intent: 'publish the page', permission: 'pages.publish' },
      { id: 'studio.expirePage', label: 'Expire', intent: 'expire the page', permission: 'pages.publish' },
      { id: 'studio.copyPageLink', label: 'Copy link', intent: 'copy the public link' },
      { id: 'studio.publishVariant', label: 'Publish variant', intent: 'publish variant {variant} as the {archetype} page', params: { variant: 'enum:A|B', archetype: 'enum:reveal|audit|walkthrough|letter' }, permission: 'pages.publish' },
      { id: 'studio.expireVariant', label: 'Expire variant', intent: 'expire variant {variant}', params: { variant: 'enum:A|B' }, permission: 'pages.publish' },
      { id: 'studio.copyVariantLink', label: 'Copy variant link', intent: 'copy the link that forces variant {variant}', params: { variant: 'enum:A|B' } },
    ],
    rules: ['R-S01', 'R-S02', 'R-S03', 'R-S04', 'R-C05', 'R-E02'], states: ['loading', 'no page yet', 'draft', 'live', 'A/B split running', 'expired', 'blocked by confidence'],
  }),
  assets: defineSpec({
    ...base, code: 'S-04', name: 'Assets & image prompts', tone: 'list',
    purpose: 'Every image and video prompt the page needs, grouped by kind, editable before generation; approve or reject each one. The image provider is not wired yet (T40).',
    layout: ['prospect nav', 'status counts', 'groups by kind', 'prompt cards (editable Textarea, aspect, notes)', 'generate (Placeholder) / approve / reject'],
    data: ['assets (read/write)', 'prospects (read)'],
    logic: ['imagePrompts(p) is the source of truth; on first visit the missing rows are inserted as queued', 'editing a prompt updates assets.prompt by id on blur', 'approve / reject set assets.status by id'],
    components: ['Card', 'Textarea', 'Badge', 'Button', 'Placeholder', 'Stat', 'Chip', 'EmptyState'],
    actions: [
      { id: 'studio.generateAsset', label: 'Generate', intent: 'generate the {kind} image', params: { kind: 'string' } },
      { id: 'studio.savePrompt', label: 'Save prompt', intent: 'save the prompt for {asset}', params: { asset: 'id' }, permission: 'prospects.write' },
      { id: 'studio.approveAsset', label: 'Approve', intent: 'approve {asset}', params: { asset: 'id' }, permission: 'prospects.write' },
      { id: 'studio.rejectAsset', label: 'Reject', intent: 'reject {asset}', params: { asset: 'id' }, permission: 'prospects.write' },
    ],
    rules: ['R-S03', 'R-P02'], states: ['loading', 'queued', 'approved', 'rejected', 'empty'],
  }),
  outreach: defineSpec({
    ...base, code: 'S-05', name: 'Outreach composer', tone: 'form',
    purpose: 'Write the message that points at the page: two or three templates per channel in English and Spanish, tokens filled from the profile and the savings, drafted into touches. Sending is not wired; "mark as sent" keeps the demo funnel honest.',
    layout: ['prospect nav', 'channel select', 'template cards', 'subject + body editor', 'filled preview', 'draft / send (Placeholder) / mark as sent', 'touches history table'],
    data: ['touches (read/write)', 'prospects (read)', 'pages (read)', 'stack_guesses (read)'],
    logic: [
      'tokens {first_name} {business} {savings_annual} {tools_cut} {page_url} {city} {industry} are filled from the prospect, savings() and the live page slug',
      'the template language follows the prospect (prospects.lang), overridable with the EN / ES picker',
      'Draft inserts a touches row with status draft and the page id; Mark as sent sets sent_at + status sent by id (R-S03)',
    ],
    components: ['Select', 'SegmentedControl', 'Textarea', 'Input', 'Field', 'Card', 'DataTable', 'Badge', 'Button', 'Placeholder', 'EmptyState'],
    actions: [
      { id: 'studio.pickChannel', label: 'Channel', intent: 'write a {channel} message', params: { channel: 'enum:cold_email|linkedin_dm|whatsapp|sms|call|warm_intro' } },
      { id: 'studio.pickTemplate', label: 'Template', intent: 'use the {template} template', params: { template: 'string' } },
      { id: 'studio.draftTouch', label: 'Draft', intent: 'draft a {channel} message', params: { channel: 'string' }, permission: 'prospects.write' },
      { id: 'studio.sendTouch', label: 'Send', intent: 'send the message' },
      { id: 'studio.markTouchSent', label: 'Mark as sent', intent: 'mark {touch} as sent', params: { touch: 'id' }, permission: 'prospects.write' },
    ],
    rules: ['R-S03', 'R-C06'], states: ['loading', 'default', 'drafted', 'sent', 'no page yet'],
  }),
} satisfies Record<string, PageSpec>;
