/**
 * Every planned page code, so the hub, canvas (D-07) and manifest show the whole map from day one.
 * A module worker replaces a stub by registering a real route at the same path (registry: built beats stub).
 * `notes[0]` names the module + task that builds it, so PageStub can say so.
 */
import type { PageSpec, Surface } from '../../specs/types';
import { defineSpec } from '../../specs/types';
import type { Role } from '../../auth/roles';
import { EVERYONE, STAFF_ROLES } from '../../auth/roles';

export interface StubDef { path: string; surface: Surface; roles: Role[]; spec: PageSpec; nav?: { label: string; icon: string; order: number; group: string; to?: string } }
const S = (code: string, name: string, purpose: string, layout: string[], data: string[], roles: Role[], module: string, task: string, actions: PageSpec['actions'] = [], components: string[] = ['Card', 'Button']): PageSpec =>
  defineSpec({ code, name, purpose, layout, data, roles, logic: [], integrations: [], components, actions, states: ['loading', 'default', 'empty'], notes: [`Built by module ${module} (${task})`] });
const A = STAFF_ROLES, ALL = EVERYONE, STRAT: Role[] = ['super_admin', 'strategist'], DEV: Role[] = ['super_admin'];

export const STUBS: StubDef[] = [
  // L- landing pages (public; own their chrome; themed per prospect)
  { path: '/p/:slug', surface: 'public', roles: ALL, spec: S('L-01', 'Reveal landing', '"We already built <Business>\'s operating system": hero reveal on phone/laptop/TV, savings stack, role views, proof, FAQ, CTA band, inline booking.', ['hero_reveal', 'savings_stack', 'role_views', 'proof', 'faq', 'cta_band', 'booking_inline', 'sticky CTA (mobile)', 'exit intent'], ['pages', 'prospects', 'stack_guesses', 'events'], ALL, 'landing', 'T12', [{ id: 'landing.openDemo', label: 'Open your demo', intent: 'open {business} demo', permission: 'demo.open' }, { id: 'landing.bookCall', label: 'Book a 15-min walkthrough', intent: 'book a walkthrough call', permission: 'booking.create' }, { id: 'landing.saveWorkspace', label: 'Save your workspace', intent: 'save my workspace with my email' }], ['DeviceMockup', 'Stat', 'Button', 'Card', 'LangToggle']) },
  { path: '/p/:slug/audit', surface: 'public', roles: ALL, spec: S('L-02', 'Savings audit landing', 'Leads with money: pre-checked tool list the prospect corrects, live savings counter, then the reveal.', ['hero (money headline)', 'stack_audit', 'savings_stack (live counter)', 'role_views', 'proof', 'cta_band', 'booking_inline'], ['pages', 'prospects', 'stack_guesses', 'events'], ALL, 'landing', 'T12', [{ id: 'landing.confirmTool', label: 'Yes, we pay for this', intent: 'confirm we use {tool}', params: { tool: 'string' } }, { id: 'landing.rejectTool', label: 'No, not us', intent: 'reject {tool}', params: { tool: 'string' } }, { id: 'landing.openDemo', label: 'Open your demo', intent: 'open {business} demo' }, { id: 'landing.bookCall', label: 'Book a walkthrough', intent: 'book a walkthrough call' }], ['DataTable', 'Chip', 'Stat', 'DeviceMockup', 'Button']) },
  { path: '/p/:slug/story', surface: 'public', roles: ALL, spec: S('L-03', 'Walkthrough landing', '"A day in the life" scroll story through each role\'s view; ends with "this is Tuesday next week if you book today".', ['hero', 'walkthrough_steps (scroll-driven)', 'role_views', 'savings_stack', 'cta_band', 'booking_inline'], ['pages', 'prospects', 'events'], ALL, 'landing', 'T12', [{ id: 'landing.openDemo', label: 'Open your demo', intent: 'open {business} demo' }, { id: 'landing.bookCall', label: 'Make it next Tuesday', intent: 'book a walkthrough call' }], ['DeviceMockup', 'Card', 'Button']) },
  { path: '/p/:slug/letter', surface: 'public', roles: ALL, spec: S('L-04', 'Letter landing', 'Short personal message from us over their branded app, one CTA. Best for hot / high-ticket warm.', ['letter', 'hero_reveal (app behind)', 'cta_band', 'booking_inline'], ['pages', 'prospects', 'events'], ALL, 'landing', 'T12', [{ id: 'landing.openDemo', label: 'Open your demo', intent: 'open {business} demo' }, { id: 'landing.bookCall', label: 'Pick a slot', intent: 'book a walkthrough call' }], ['DeviceMockup', 'Button']) },
  { path: '/p/:slug/expired', surface: 'public', roles: ALL, spec: S('L-05', 'Expired / generic page', 'Shown when a page is past expires_at or the slug is unknown: honest message and a way to book or request a fresh workspace.', ['message', 'request new workspace', 'book a call'], ['pages'], ALL, 'landing', 'T12', [{ id: 'landing.requestRefresh', label: 'Request a fresh workspace', intent: 'request a new workspace' }, { id: 'landing.bookCall', label: 'Book a call', intent: 'book a walkthrough call' }]) },
  // C- the prospect's tailored OS demo
  { path: '/demo/:prospectId', surface: 'demo', roles: ALL, spec: S('C-01', 'OS demo shell', 'The prospect\'s operating system, themed to them: role switcher for every business + life role, phone / desktop / TV layouts, EN/ES.', ['top bar (their logo, role switcher, lang)', 'role home', 'nav per role', 'save workspace prompt at moment of value'], ['prospects', 'pages', 'events'], ALL, 'os-demo', 'T13', [{ id: 'demo.switchRole', label: 'Switch role', intent: 'view as {role}', params: { role: 'string' } }, { id: 'demo.saveWorkspace', label: 'Save your workspace', intent: 'save my workspace' }, { id: 'demo.bookCall', label: 'Book a walkthrough', intent: 'book a walkthrough call' }], ['RoleSwitcher', 'Stat', 'Card', 'Tabs', 'LangToggle']) },
  { path: '/demo/:prospectId/role/:role', surface: 'demo', roles: ALL, spec: S('C-02', 'Role home', 'One role\'s view: 3+ widgets from deriveRoleViews themed to the industry (KPI, calendar, list, chat, chart, doc).', ['headline', 'widgets grid', 'today', 'quick actions'], ['prospects'], ALL, 'os-demo', 'T13', [{ id: 'demo.openWidget', label: 'Open', intent: 'open {widget}', params: { widget: 'string' } }], ['Stat', 'Card', 'DataTable']) },
  { path: '/demo/:prospectId/departments', surface: 'demo', roles: ALL, spec: S('C-03', 'Departments board', 'Their departments (from the industry catalog) as a board with people, tasks and KPIs.', ['department columns', 'people', 'open items'], ['prospects'], ALL, 'os-demo', 'T13', [], ['Card', 'Badge']) },
  { path: '/demo/:prospectId/comms', surface: 'demo', roles: ALL, spec: S('C-04', 'Comms inbox', 'Unified inbox mock: calls, email, SMS, WhatsApp in one thread list, themed sample messages.', ['channel filter', 'thread list', 'thread', 'composer (Placeholder)'], ['prospects'], ALL, 'os-demo', 'T13', [{ id: 'demo.reply', label: 'Reply', intent: 'reply to {thread}', params: { thread: 'id' } }], ['Tabs', 'Card', 'Textarea', 'Placeholder']) },
  { path: '/demo/:prospectId/money', surface: 'demo', roles: ALL, spec: S('C-05', 'Money', 'Savings (their crossed-out stack) plus payments / payroll sample views.', ['savings stack', 'cash today', 'payments list', 'payroll (Placeholder)'], ['prospects', 'stack_guesses'], ALL, 'os-demo', 'T13', [], ['Stat', 'DataTable', 'Placeholder']) },
  { path: '/demo/:prospectId/life', surface: 'demo', roles: ALL, spec: S('C-06', 'Family / life view', 'Views for the people in their life: partner, kids, accountant, coach; shared calendar and lists.', ['people row', 'shared calendar', 'lists', 'chat'], ['prospects'], ALL, 'os-demo', 'T13', [], ['Avatar', 'Card']) },
  { path: '/demo/:prospectId/settings', surface: 'demo', roles: ALL, spec: S('C-07', 'Settings & roles', 'Their roles and permissions, brand palette, language: shows that it is theirs and configurable.', ['roles table', 'brand', 'language', 'invite (Placeholder)'], ['prospects'], ALL, 'os-demo', 'T13', [{ id: 'demo.invite', label: 'Invite', intent: 'invite {person}', params: { person: 'string' } }], ['DataTable', 'Placeholder', 'LangToggle']) },
  // B- booking
  { path: '/book/:prospectId', surface: 'public', roles: ALL, spec: S('B-01', 'Book a call', 'Inline 15-min slot picker (mock calendar), name/email at the moment of value, writes bookings + booking_started/confirmed events.', ['slot grid (next 7 days)', 'details form', 'confirm'], ['bookings', 'prospects', 'events'], ALL, 'booking', 'T14', [{ id: 'booking.pickSlot', label: 'Pick a slot', intent: 'book {slot}', params: { slot: 'date' }, permission: 'booking.create' }, { id: 'booking.confirm', label: 'Confirm', intent: 'confirm my booking', permission: 'booking.create' }], ['Card', 'Field', 'Input', 'Button']) },
  { path: '/book/:prospectId/confirmed', surface: 'public', roles: ALL, spec: S('B-02', 'Booking confirmed', 'Confirmation with calendar add (Placeholder until a real provider) and a link back to their demo.', ['confirmation', 'add to calendar (Placeholder)', 'back to demo'], ['bookings'], ALL, 'booking', 'T14', [{ id: 'booking.addToCalendar', label: 'Add to calendar', intent: 'add the call to my calendar' }], ['Card', 'Placeholder']) },
  // S- studio
  { path: '/studio', surface: 'studio', roles: STRAT, nav: { label: 'Prospects', icon: 'users', order: 1, group: 'studio' }, spec: S('S-01', 'Prospects list', 'Every prospect with warmth, confidence, live page, last event; filters; new prospect.', ['filters', 'DataTable', 'new prospect'], ['prospects', 'pages', 'events'], STRAT, 'studio', 'T11', [{ id: 'studio.newProspect', label: 'New prospect', intent: 'create a prospect', permission: 'prospects.write' }, { id: 'studio.openProspect', label: 'Open', intent: 'open prospect {name}', params: { name: 'string' } }], ['DataTable', 'Chip', 'Button', 'Badge']) },
  { path: '/studio/prospects/:id', surface: 'studio', roles: STRAT, spec: S('S-02', 'Prospect profile + AI intake', 'Profile, confidence meter, nextQuestions() as an adaptive intake form, applyAnswer() updates; stack guesses to confirm/reject; enricher status (LLM not wired).', ['header', 'confidence', 'intake questions', 'stack guesses', 'roles', 'style'], ['prospects', 'stack_guesses'], STRAT, 'studio', 'T11', [{ id: 'studio.answerQuestion', label: 'Save answer', intent: 'answer {field} with {value}', params: { field: 'string', value: 'string' }, permission: 'prospects.write' }, { id: 'studio.confirmTool', label: 'Confirm tool', intent: 'confirm {tool}', params: { tool: 'string' }, permission: 'prospects.write' }, { id: 'studio.runEnricher', label: 'Enrich with AI', intent: 'enrich this prospect', permission: 'prospects.write' }], ['ProgressBar', 'Field', 'Input', 'Select', 'DataTable', 'Placeholder']) },
  { path: '/studio/prospects/:id/compose', surface: 'studio', roles: STRAT, spec: S('S-03', 'Page composer', 'pickArchetype() ranking with reasons, composePage() preview in ViewportFrame at 390 / 1280, variant, publish (14 days).', ['archetype ranking', 'preview', 'variant', 'publish'], ['prospects', 'pages', 'stack_guesses'], STRAT, 'studio', 'T11', [{ id: 'studio.pickArchetype', label: 'Use this archetype', intent: 'use the {archetype} archetype', params: { archetype: 'enum:reveal|audit|walkthrough|letter' }, permission: 'pages.publish' }, { id: 'studio.publishPage', label: 'Publish', intent: 'publish the page', permission: 'pages.publish' }, { id: 'studio.expirePage', label: 'Expire', intent: 'expire the page', permission: 'pages.publish' }], ['ViewportFrame', 'SegmentedControl', 'Button', 'Badge']) },
  { path: '/studio/prospects/:id/assets', surface: 'studio', roles: STRAT, spec: S('S-04', 'Assets & image prompts', 'imagePrompts() per kind with status; generate is a Placeholder until the provider is wired (T40); approve / reject.', ['prompt cards by kind', 'generate (Placeholder)', 'approve / reject'], ['assets', 'prospects'], STRAT, 'studio', 'T11', [{ id: 'studio.generateAsset', label: 'Generate', intent: 'generate the {kind} image', params: { kind: 'string' } }, { id: 'studio.approveAsset', label: 'Approve', intent: 'approve {asset}', params: { asset: 'id' }, permission: 'prospects.write' }], ['Card', 'Textarea', 'Placeholder', 'Badge']) },
  { path: '/studio/prospects/:id/outreach', surface: 'studio', roles: STRAT, spec: S('S-05', 'Outreach composer', 'Cold / warm messages per channel pointing at the page; templates filled with prospect tokens; send is a Placeholder.', ['channel', 'template', 'preview', 'send (Placeholder)', 'touches history'], ['touches', 'prospects', 'pages'], STRAT, 'studio', 'T11', [{ id: 'studio.draftTouch', label: 'Draft', intent: 'draft a {channel} message', params: { channel: 'string' }, permission: 'prospects.write' }, { id: 'studio.sendTouch', label: 'Send', intent: 'send the message' }], ['Select', 'Textarea', 'DataTable', 'Placeholder']) },
  // A- admin / analytics
  { path: '/admin', surface: 'admin', roles: A, nav: { label: 'Funnel', icon: 'chart', order: 1, group: 'admin' }, spec: S('A-01', 'Funnel overview', 'outreach_open -> view -> demo_open -> booking per archetype / warmth; A/B by variant.', ['KPI row', 'funnel', 'by archetype', 'recent'], ['events', 'pages', 'prospects', 'bookings'], A, 'admin', 'T15', [{ id: 'admin.filterFunnel', label: 'Filter', intent: 'filter the funnel by {archetype}', params: { archetype: 'string' }, permission: 'events.read' }], ['Stat', 'DataTable', 'Chip']) },
  { path: '/admin/prospects/:id', surface: 'admin', roles: A, spec: S('A-02', 'Prospect timeline', 'Every touch, view, section, CTA, demo role switch and booking for one prospect, in order; adaptFromEvents() recommendations.', ['header', 'timeline', 'recommendations'], ['events', 'touches', 'bookings', 'prospects', 'pages'], A, 'admin', 'T15', [{ id: 'admin.applyRecommendation', label: 'Apply', intent: 'apply recommendation {n}', params: { n: 'number' }, permission: 'pages.publish' }], ['Card', 'Badge']) },
  { path: '/admin/events', surface: 'admin', roles: A, nav: { label: 'Events', icon: 'list', order: 2, group: 'admin' }, spec: S('A-03', 'Events log', 'Raw events table with filters by type / page / session.', ['filters', 'DataTable'], ['events'], A, 'admin', 'T15', [], ['DataTable', 'Chip']) },
  { path: '/admin/outreach', surface: 'admin', roles: A, nav: { label: 'Outreach', icon: 'mail', order: 3, group: 'admin' }, spec: S('A-04', 'Outreach board', 'Touches by status (draft, sent, opened, clicked, replied) per channel.', ['status columns', 'cards'], ['touches', 'prospects'], A, 'admin', 'T15', [{ id: 'admin.moveTouch', label: 'Move', intent: 'mark {touch} as {status}', params: { touch: 'id', status: 'string' }, permission: 'prospects.write' }], ['Card', 'Badge']) },
  { path: '/admin/bookings', surface: 'admin', roles: A, nav: { label: 'Bookings', icon: 'calendar', order: 4, group: 'admin' }, spec: S('A-05', 'Bookings', 'Upcoming and past walkthrough calls with status changes.', ['upcoming', 'past', 'status'], ['bookings', 'prospects'], A, 'admin', 'T15', [{ id: 'admin.setBookingStatus', label: 'Set status', intent: 'mark booking {id} {status}', params: { id: 'id', status: 'enum:requested|confirmed|cancelled|completed' }, permission: 'prospects.write' }], ['DataTable', 'Select']) },
  // K- plan
  { path: '/plan', surface: 'plan', roles: A, nav: { label: 'Kanban', icon: 'kanban', order: 1, group: 'plan' }, spec: S('K-01', 'Plan Kanban', 'tasks by status (backlog / doing / done / blocked / awaiting Justin) with model badge, codes, dependencies; move with buttons (not drag-only).', ['lanes', 'cards', 'move'], ['tasks'], A, 'plan', 'T10', [{ id: 'plan.moveTask', label: 'Move', intent: 'move {task} to {status}', params: { task: 'id', status: 'string' }, permission: 'plan.edit' }], ['Card', 'Badge', 'Select']) },
  { path: '/plan/list', surface: 'plan', roles: A, nav: { label: 'List', icon: 'list', order: 2, group: 'plan' }, spec: S('K-02', 'Plan list', 'Sortable table of every task: id, title, module, codes, model, phase, depends on, status.', ['filters', 'DataTable'], ['tasks'], A, 'plan', 'T10', [], ['DataTable', 'Chip']) },
  { path: '/plan/timeline', surface: 'plan', roles: A, nav: { label: 'Timeline', icon: 'chart', order: 3, group: 'plan' }, spec: S('K-03', 'Plan timeline', 'Dependency graph: phases as columns, tasks as nodes, depends_on as edges (SVG); tasks are bound by dependencies, not calendar days.', ['phase columns', 'nodes', 'edges', 'legend'], ['tasks'], A, 'plan', 'T10', [{ id: 'plan.focusTask', label: 'Focus', intent: 'focus task {task}', params: { task: 'id' } }], ['Card', 'Badge']) },
  { path: '/plan/tasks/:id', surface: 'plan', roles: A, spec: S('K-04', 'Task detail', 'One task: notes, codes, dependencies both ways, status change, model.', ['header', 'dependencies', 'notes', 'status'], ['tasks'], A, 'plan', 'T10', [{ id: 'plan.setStatus', label: 'Set status', intent: 'set {task} to {status}', params: { task: 'id', status: 'string' }, permission: 'plan.edit' }], ['Card', 'Select', 'Badge']) },
  // W- our website
  { path: '/site', surface: 'public', roles: ALL, spec: S('W-01', 'Website home', 'Imagine\'s public site: the offer (an OS already built for you), sample prospect pages, how it works, pricing.', ['hero', 'samples', 'how', 'pricing teaser', 'footer'], ['prospects'], ALL, 'website', 'T16', [{ id: 'site.seeSample', label: 'See a sample', intent: 'open a sample landing page' }, { id: 'site.startPurchase', label: 'Get yours', intent: 'start the purchase flow' }], ['DeviceMockup', 'Card', 'Button']) },
  { path: '/site/how', surface: 'public', roles: ALL, spec: S('W-02', 'How it works', 'Intake -> stack guess -> compose -> demo -> book; the AI methodology explained.', ['steps', 'engine diagram', 'faq'], [], ALL, 'website', 'T16', [], ['Card']) },
  { path: '/site/pricing', surface: 'public', roles: ALL, spec: S('W-03', 'Pricing + purchase flow', 'starter / team / multi bands with the savings math; purchase flow is a Placeholder until Stripe (T51).', ['bands', 'savings calculator', 'checkout (Placeholder)'], ['prospects'], ALL, 'website', 'T16', [{ id: 'site.choosePlan', label: 'Choose plan', intent: 'choose the {band} plan', params: { band: 'enum:starter|team|multi' } }, { id: 'site.checkout', label: 'Checkout', intent: 'pay for the plan' }], ['Card', 'Stat', 'Placeholder']) },
  // R- proposal
  { path: '/proposal/:prospectId', surface: 'public', roles: ALL, spec: S('R-01', 'Client proposal view', 'The full stack for one prospect: their OS, savings, roles, timeline, price, next steps; printable.', ['cover', 'what you get', 'savings', 'roles', 'timeline', 'price', 'accept (Placeholder)'], ['prospects', 'stack_guesses', 'pages'], ALL, 'proposal', 'T16', [{ id: 'proposal.accept', label: 'Accept proposal', intent: 'accept the proposal' }, { id: 'proposal.print', label: 'Print', intent: 'print the proposal', permission: 'proposal.read' }], ['Card', 'Stat', 'DataTable', 'Placeholder']) },
  // M- ops manual
  { path: '/manual', surface: 'manual', roles: A, nav: { label: 'Manual', icon: 'book', order: 1, group: 'manual' }, spec: S('M-01', 'Ops manual home', 'How we run Lead Magnet: chapters EN/ES rendered from docs/ops-manual.', ['chapter list'], [], A, 'manual', 'T33', [], ['Card']) },
  { path: '/manual/intake', surface: 'manual', roles: A, nav: { label: 'Intake', icon: 'sparkles', order: 2, group: 'manual' }, spec: S('M-02', 'Chapter: intake & research', 'How to research a prospect and run the adaptive intake.', ['chapter'], [], A, 'manual', 'T33') },
  { path: '/manual/compose', surface: 'manual', roles: A, nav: { label: 'Compose & publish', icon: 'wand', order: 3, group: 'manual' }, spec: S('M-03', 'Chapter: compose & publish', 'Choosing an archetype, previewing, publishing, the 14-day rule.', ['chapter'], [], A, 'manual', 'T33') },
  { path: '/manual/outreach', surface: 'manual', roles: A, nav: { label: 'Outreach', icon: 'mail', order: 4, group: 'manual' }, spec: S('M-04', 'Chapter: outreach & follow-up', 'Channels, cadences, what to say, reading the funnel.', ['chapter'], [], A, 'manual', 'T33') },
  { path: '/manual/calls', surface: 'manual', roles: A, nav: { label: 'Walkthrough calls', icon: 'phone', order: 5, group: 'manual' }, spec: S('M-05', 'Chapter: walkthrough calls', 'Running the 15-minute walkthrough and the proposal.', ['chapter'], [], A, 'manual', 'T33') },
];
export const DEV_ONLY = DEV;
