import type { Industry, IndustryKey, StackItem } from '../types';

const s = (tool: string, category: string, monthly_cost: number, replaced_by: string, prevalence = 0.7, extra: Partial<StackItem> = {}): StackItem => ({ tool, category, monthly_cost, replaced_by, prevalence, ...extra });
const bi = (en: string, es: string) => ({ en, es });
/** Shared tools most small businesses pay for. Prices are plausible list prices (USD / month) in 2026. */
const COMMON: StackItem[] = [
  s('Google Workspace', 'Email & files', 14, 'Mail & Docs', 0.85, { per_seat: true }),
  s('QuickBooks Online', 'Accounting', 90, 'Money', 0.8),
  s('Calendly', 'Scheduling', 12, 'Calendar', 0.5, { per_seat: true }),
  s('DocuSign', 'E-sign', 45, 'Sign', 0.45),
  s('Mailchimp', 'Email marketing', 60, 'Campaigns', 0.6),
  s('Canva Pro', 'Design', 15, 'Studio', 0.55),
  s('Slack', 'Team chat', 8.75, 'Chat', 0.4, { per_seat: true }),
  s('Zoom', 'Video calls', 16, 'Calls & video', 0.5),
  s('RingCentral', 'Phone system', 30, 'Calls', 0.4, { per_seat: true }),
  s('Dropbox', 'File storage', 20, 'Files', 0.3),
];

export const INDUSTRIES: Record<IndustryKey, Industry> = {
  pet_care: {
    key: 'pet_care', label: bi('Pet care (daycare, boarding, grooming)', 'Cuidado de mascotas (guardería, hotel, peluquería)'),
    departments: [bi('Front desk', 'Recepción'), bi('Daycare floor', 'Guardería'), bi('Grooming', 'Peluquería'), bi('Boarding', 'Hospedaje'), bi('Marketing', 'Marketing'), bi('Money', 'Finanzas')],
    business_roles: ['owner', 'manager', 'front desk', 'handler', 'groomer'], life_roles: ['owner', 'spouse/partner', 'kids', 'accountant', 'vet partner'],
    stack: [s('Gingr', 'Pet software', 165, 'Bookings & pets', 0.7, { per_location: true }), s('PetExec', 'Pet software', 129, 'Bookings & pets', 0.3, { per_location: true }), s('Homebase', 'Scheduling & payroll', 24.95, 'Team', 0.6, { per_location: true }), s('Square', 'Payments', 60, 'Payments', 0.7), ...COMMON],
    pains: [bi('Vaccine records chased by hand', 'Certificados de vacunas a mano'), bi('Double bookings on busy weekends', 'Reservas dobles los fines de semana'), bi('Report cards texted from personal phones', 'Reportes desde celulares personales')],
    kpis: [{ label: bi('Dogs in today', 'Perros hoy'), sample: '42' }, { label: bi('Occupancy', 'Ocupación'), sample: '86%' }, { label: bi('Vaccines expiring', 'Vacunas por vencer'), sample: '7' }],
    motifs: ['happy dogs mid-play', 'sunlit play yard', 'grooming table', 'report card on a phone'], verbs: bi('runs the daycare', 'lleva la guardería'),
  },
  dental: {
    key: 'dental', label: bi('Dental practice', 'Clínica dental'),
    departments: [bi('Front office', 'Recepción'), bi('Hygiene', 'Higiene'), bi('Clinical', 'Clínica'), bi('Billing & insurance', 'Facturación y seguros'), bi('Marketing', 'Marketing')],
    business_roles: ['owner dentist', 'office manager', 'front office', 'hygienist', 'associate dentist', 'billing'], life_roles: ['owner', 'spouse/partner', 'kids', 'accountant', 'practice consultant'],
    stack: [s('Dentrix', 'Practice management', 450, 'Patients & charts', 0.55, { per_location: true }), s('Open Dental', 'Practice management', 179, 'Patients & charts', 0.35, { per_location: true }), s('Weave', 'Patient comms', 399, 'Comms', 0.5, { per_location: true }), s('Solutionreach', 'Reminders', 329, 'Comms', 0.3, { per_location: true }), s('CareCredit portal', 'Financing', 0, 'Money', 0.4), ...COMMON],
    pains: [bi('No-shows eat 12% of chair time', 'Las inasistencias comen 12% del tiempo de sillón'), bi('Insurance verification by phone', 'Verificación de seguros por teléfono'), bi('Recall lists in spreadsheets', 'Listas de recall en hojas de cálculo')],
    kpis: [{ label: bi('Chairs booked today', 'Sillones ocupados hoy'), sample: '9 / 10' }, { label: bi('Recall due', 'Recall pendiente'), sample: '134' }, { label: bi('Claims outstanding', 'Reclamos pendientes'), sample: '$48,200' }],
    motifs: ['bright modern operatory', 'smiling patient', 'tablet at reception', 'two clinic storefronts'], verbs: bi('runs the practice', 'dirige la clínica'),
  },
  restaurant: {
    key: 'restaurant', label: bi('Restaurant / restaurant group', 'Restaurante / grupo de restaurantes'),
    departments: [bi('Front of house', 'Sala'), bi('Kitchen', 'Cocina'), bi('Bar', 'Bar'), bi('Events & catering', 'Eventos y catering'), bi('Marketing', 'Marketing'), bi('Money', 'Finanzas')],
    business_roles: ['owner', 'general manager', 'chef', 'shift lead', 'host', 'events manager'], life_roles: ['owner', 'spouse/partner', 'kids', 'accountant', 'investor'],
    stack: [s('Toast POS', 'POS', 165, 'Orders & POS', 0.7, { per_location: true }), s('7shifts', 'Scheduling', 34.99, 'Team', 0.6, { per_location: true }), s('Homebase', 'Scheduling & payroll', 24.95, 'Team', 0.3, { per_location: true }), s('OpenTable', 'Reservations', 249, 'Reservations', 0.5, { per_location: true }), s('Resy', 'Reservations', 249, 'Reservations', 0.3, { per_location: true }), s('MarketMan', 'Inventory', 239, 'Inventory', 0.35, { per_location: true }), s('Tripleseat', 'Events', 250, 'Events', 0.3), ...COMMON],
    pains: [bi('Three logins to see one night', 'Tres logins para ver una noche'), bi('Schedules re-typed into payroll', 'Horarios re-tipeados en la nómina'), bi('Guest data trapped in the reservation app', 'Datos de clientes atrapados en la app de reservas')],
    kpis: [{ label: bi('Covers tonight', 'Cubiertos esta noche'), sample: '212' }, { label: bi('Labor %', '% Laboral'), sample: '27.4%' }, { label: bi('Food cost', 'Costo de alimentos'), sample: '31%' }],
    motifs: ['warm dining room at golden hour', 'chef plating', 'reservation book on a tablet', 'three storefronts on one map'], verbs: bi('runs the restaurants', 'lleva los restaurantes'),
  },
  gym_wellness: {
    key: 'gym_wellness', label: bi('Gym / wellness studio', 'Gimnasio / estudio de bienestar'),
    departments: [bi('Front desk', 'Recepción'), bi('Coaching', 'Coaching'), bi('Memberships', 'Membresías'), bi('Classes', 'Clases'), bi('Marketing', 'Marketing')],
    business_roles: ['owner', 'studio manager', 'coach', 'front desk', 'sales'], life_roles: ['owner', 'spouse/partner', 'kids', 'accountant', 'nutritionist'],
    stack: [s('Mindbody', 'Studio software', 279, 'Members & classes', 0.6, { per_location: true }), s('Mariana Tek', 'Studio software', 350, 'Members & classes', 0.2, { per_location: true }), s('Trainerize', 'Coaching app', 90, 'Coaching', 0.4), s('Gympass listing', 'Aggregator', 0, 'Members', 0.3), ...COMMON],
    pains: [bi('Members churn silently', 'Los miembros se van en silencio'), bi('Waitlists managed by text', 'Listas de espera por mensaje'), bi('Coaches on a separate app', 'Los coaches en otra app')],
    kpis: [{ label: bi('Active members', 'Miembros activos'), sample: '512' }, { label: bi('Class fill', 'Ocupación de clases'), sample: '78%' }, { label: bi('At-risk this week', 'En riesgo esta semana'), sample: '19' }],
    motifs: ['sunrise class', 'coach with tablet', 'member check-in screen', 'community wall'], verbs: bi('runs the studio', 'dirige el estudio'),
  },
  real_estate: {
    key: 'real_estate', label: bi('Real estate brokerage', 'Inmobiliaria'),
    departments: [bi('Agents', 'Agentes'), bi('Transactions', 'Transacciones'), bi('Marketing', 'Marketing'), bi('Recruiting', 'Reclutamiento'), bi('Money', 'Finanzas')],
    business_roles: ['broker owner', 'team lead', 'agent', 'transaction coordinator', 'marketing'], life_roles: ['owner', 'spouse/partner', 'kids', 'accountant', 'lender partner'],
    stack: [s('Follow Up Boss', 'CRM', 69, 'CRM', 0.5, { per_seat: true }), s('kvCORE', 'CRM & sites', 499, 'CRM', 0.3), s('Dotloop', 'Transactions', 31.99, 'Deals', 0.5, { per_seat: true }), s('BombBomb', 'Video email', 39, 'Campaigns', 0.3, { per_seat: true }), ...COMMON],
    pains: [bi('Leads fall between agents', 'Los leads se pierden entre agentes'), bi('Deal docs in five places', 'Documentos en cinco lugares'), bi('Agents build their own brand tools', 'Cada agente arma su propia marca')],
    kpis: [{ label: bi('Active listings', 'Propiedades activas'), sample: '38' }, { label: bi('Under contract', 'Bajo contrato'), sample: '14' }, { label: bi('Leads this week', 'Leads esta semana'), sample: '61' }],
    motifs: ['sunlit living room', 'agent with client at door', 'deal pipeline board', 'city skyline'], verbs: bi('runs the brokerage', 'dirige la inmobiliaria'),
  },
  law_firm: {
    key: 'law_firm', label: bi('Law firm', 'Bufete de abogados'),
    departments: [bi('Intake', 'Admisión'), bi('Matters', 'Casos'), bi('Billing', 'Facturación'), bi('Documents', 'Documentos'), bi('Marketing', 'Marketing')],
    business_roles: ['managing partner', 'associate', 'paralegal', 'intake', 'billing'], life_roles: ['owner', 'spouse/partner', 'kids', 'accountant', 'of counsel'],
    stack: [s('Clio', 'Practice management', 129, 'Matters', 0.6, { per_seat: true }), s('MyCase', 'Practice management', 89, 'Matters', 0.25, { per_seat: true }), s('Lawmatics', 'Intake CRM', 199, 'Intake', 0.3), s('LawPay', 'Payments', 19, 'Payments', 0.5), ...COMMON],
    pains: [bi('Intake calls not logged', 'Llamadas de admisión sin registro'), bi('Unbilled hours', 'Horas sin facturar'), bi('Documents drafted from old templates', 'Documentos de plantillas viejas')],
    kpis: [{ label: bi('Open matters', 'Casos abiertos'), sample: '73' }, { label: bi('Unbilled hours', 'Horas sin facturar'), sample: '118' }, { label: bi('Intake this week', 'Admisiones esta semana'), sample: '22' }],
    motifs: ['quiet office library', 'partner reviewing on a tablet', 'matter timeline', 'signature ceremony'], verbs: bi('runs the firm', 'dirige el bufete'),
  },
  salon_spa: {
    key: 'salon_spa', label: bi('Salon / spa', 'Salón / spa'),
    departments: [bi('Front desk', 'Recepción'), bi('Stylists', 'Estilistas'), bi('Retail', 'Retail'), bi('Marketing', 'Marketing')],
    business_roles: ['owner', 'manager', 'stylist', 'front desk', 'esthetician'], life_roles: ['owner', 'spouse/partner', 'kids', 'accountant', 'educator'],
    stack: [s('Vagaro', 'Salon software', 45, 'Bookings', 0.45, { per_location: true }), s('Boulevard', 'Salon software', 175, 'Bookings', 0.3, { per_location: true }), s('Fresha', 'Salon software', 0, 'Bookings', 0.25), s('Square', 'Payments', 60, 'Payments', 0.6), ...COMMON],
    pains: [bi('Rebooking left to chance', 'Re-agendar queda al azar'), bi('Stylist schedules on paper', 'Horarios de estilistas en papel'), bi('Retail inventory guessed', 'Inventario a ojo')],
    kpis: [{ label: bi('Appointments today', 'Citas hoy'), sample: '58' }, { label: bi('Rebook rate', 'Tasa de re-agenda'), sample: '64%' }, { label: bi('Retail attach', 'Venta cruzada retail'), sample: '22%' }],
    motifs: ['soft-lit salon chair', 'stylist with client', 'product shelf', 'appointment grid'], verbs: bi('runs the salon', 'lleva el salón'),
  },
  home_services: {
    key: 'home_services', label: bi('Home services contractor', 'Contratista de servicios para el hogar'),
    departments: [bi('Dispatch', 'Despacho'), bi('Field crews', 'Cuadrillas'), bi('Estimates', 'Presupuestos'), bi('Billing', 'Facturación'), bi('Marketing', 'Marketing')],
    business_roles: ['owner', 'office manager', 'dispatcher', 'technician', 'estimator'], life_roles: ['owner', 'spouse/partner', 'kids', 'accountant', 'supplier rep'],
    stack: [s('ServiceTitan', 'Field service', 398, 'Jobs & dispatch', 0.4, { per_seat: true }), s('Jobber', 'Field service', 169, 'Jobs & dispatch', 0.4), s('Housecall Pro', 'Field service', 189, 'Jobs & dispatch', 0.3), s('Angi Leads', 'Lead gen', 300, 'Leads', 0.4), ...COMMON],
    pains: [bi('Estimates lost in text threads', 'Presupuestos perdidos en mensajes'), bi('Crews called for every change', 'Llamar a la cuadrilla por cada cambio'), bi('Invoices weeks late', 'Facturas con semanas de retraso')],
    kpis: [{ label: bi('Jobs today', 'Trabajos hoy'), sample: '17' }, { label: bi('Estimates open', 'Presupuestos abiertos'), sample: '$86,400' }, { label: bi('Avg days to invoice', 'Días para facturar'), sample: '1.2' }],
    motifs: ['branded van at dawn', 'tech with tablet at a door', 'dispatch map', 'before/after job'], verbs: bi('runs the company', 'lleva la empresa'),
  },
  auto_shop: {
    key: 'auto_shop', label: bi('Auto repair shop', 'Taller mecánico'),
    departments: [bi('Service desk', 'Recepción de servicio'), bi('Bays', 'Bahías'), bi('Parts', 'Refacciones'), bi('Billing', 'Facturación')],
    business_roles: ['owner', 'service advisor', 'technician', 'parts', 'office'], life_roles: ['owner', 'spouse/partner', 'kids', 'accountant', 'parts supplier'],
    stack: [s('Tekmetric', 'Shop management', 299, 'Repair orders', 0.4, { per_location: true }), s('Shop-Ware', 'Shop management', 349, 'Repair orders', 0.3, { per_location: true }), s('Mitchell 1', 'Repair data', 189, 'Repair orders', 0.4), s('Kukui', 'Marketing', 299, 'Campaigns', 0.3), ...COMMON],
    pains: [bi('Approvals by phone tag', 'Aprobaciones a puro teléfono'), bi('Parts ordered twice', 'Refacciones pedidas dos veces'), bi('No reminders for next service', 'Sin recordatorios de servicio')],
    kpis: [{ label: bi('Cars in bays', 'Autos en bahías'), sample: '11' }, { label: bi('ARO', 'Ticket promedio'), sample: '$486' }, { label: bi('Approvals waiting', 'Aprobaciones pendientes'), sample: '6' }],
    motifs: ['clean shop floor', 'advisor showing tablet to customer', 'lift with car', 'digital inspection'], verbs: bi('runs the shop', 'lleva el taller'),
  },
  med_spa: {
    key: 'med_spa', label: bi('Med spa / aesthetics', 'Med spa / estética'),
    departments: [bi('Front desk', 'Recepción'), bi('Providers', 'Proveedores'), bi('Memberships', 'Membresías'), bi('Marketing', 'Marketing'), bi('Compliance', 'Cumplimiento')],
    business_roles: ['owner', 'medical director', 'nurse injector', 'esthetician', 'front desk', 'patient coordinator'], life_roles: ['owner', 'spouse/partner', 'kids', 'accountant', 'medical director'],
    stack: [s('Zenoti', 'Spa software', 400, 'Patients & bookings', 0.35, { per_location: true }), s('Boulevard', 'Spa software', 175, 'Patients & bookings', 0.3, { per_location: true }), s('Aesthetic Record', 'EMR', 149, 'Charts', 0.4), s('Podium', 'Reviews & messaging', 399, 'Comms', 0.35), ...COMMON],
    pains: [bi('Consents on paper', 'Consentimientos en papel'), bi('Memberships tracked by hand', 'Membresías a mano'), bi('Before/after photos on phones', 'Fotos antes/después en celulares')],
    kpis: [{ label: bi('Treatments today', 'Tratamientos hoy'), sample: '31' }, { label: bi('Members', 'Miembros'), sample: '240' }, { label: bi('Rebook rate', 'Re-agenda'), sample: '71%' }],
    motifs: ['serene treatment room', 'provider consult on tablet', 'membership card', 'glowing storefront'], verbs: bi('runs the spa', 'dirige el spa'),
  },
  other: {
    key: 'other', label: bi('Other small business', 'Otro negocio'),
    departments: [bi('Operations', 'Operaciones'), bi('Sales', 'Ventas'), bi('Marketing', 'Marketing'), bi('Money', 'Finanzas')],
    business_roles: ['owner', 'manager', 'staff'], life_roles: ['owner', 'spouse/partner', 'kids', 'accountant'],
    stack: [s('HubSpot Starter', 'CRM', 20, 'CRM', 0.4, { per_seat: true }), ...COMMON],
    pains: [bi('Too many tools', 'Demasiadas herramientas'), bi('Nothing talks to anything', 'Nada se conecta con nada')],
    kpis: [{ label: bi('Open tasks', 'Tareas abiertas'), sample: '24' }, { label: bi('Revenue MTD', 'Ingresos del mes'), sample: '$41,900' }],
    motifs: ['owner at a desk with morning light', 'team standup', 'dashboard on a TV'], verbs: bi('runs the business', 'lleva el negocio'),
  },
};
export const industry = (key: string): Industry => INDUSTRIES[(key in INDUSTRIES ? key : 'other') as IndustryKey];
export const INDUSTRY_KEYS = Object.keys(INDUSTRIES) as IndustryKey[];
