import { createElement as h } from 'react';
import { defineMeta } from '../../../design/meta';
import { Field } from './Field';
import { Input } from '../../atom/Input/Input';
import { Button } from '../../atom/Button/Button';
import { IconButton } from '../../atom/IconButton/IconButton';
export default defineMeta({ tier: 'molecule', name: 'Field', description: 'Label + control + hint / error wrapper; wires id and aria-describedby. `action` puts a 44 px control beside the input.', props: [{ name: 'label', type: 'string', required: true, description: '' }, { name: 'hint', type: 'string', description: '' }, { name: 'error', type: 'string', description: 'Shown as role=alert; sets invalid on the child' }, { name: 'action', type: 'ReactNode', description: 'Button / IconButton rendered beside the input (no wrapper needed)' }, { name: 'inline', type: 'boolean', description: 'Label left of the control' }], states: ['default', 'error', 'with action'],
  usages: [{ title: 'Fields', render: () => h('div', { className: 'stack', style: { maxWidth: 360 } }, h(Field, { label: 'Business name', hint: 'As it appears on their sign', required: true }, h(Input, { placeholder: 'Paws & Play Austin' })), h(Field, { label: 'Email', error: 'Enter a valid email' }, h(Input, { defaultValue: 'maya@' }))) },
    { title: 'Action slot', render: () => h('div', { className: 'stack', style: { maxWidth: 420 } }, h(Field, { label: 'Website', hint: 'We read the stack from it', action: h(Button, { variant: 'outline', icon: 'sparkles' }, 'Guess') }, h(Input, { defaultValue: 'pawsandplay.com' })), h(Field, { label: 'Public link', action: h(IconButton, { icon: 'external-link', label: 'Open link', variant: 'outline' }) }, h(Input, { readOnly: true, defaultValue: 'https://imagine-os.github.io/lead-magnet/#/p/paws-and-play-austin' }))) }],
  a11y: ['Real <label for>; error is role=alert.', 'The action keeps its own accessible name (Button text or IconButton label) and its 44 px box.'], usedBy: ['D-02', 'D-09', 'S-02'] });
