import { createElement as h } from 'react';
import { defineMeta } from '../../../design/meta';
import { Button } from './Button';
export default defineMeta({ tier: 'atom', name: 'Button', description: 'The one button for every surface. primary (electric), accent (lime CTA for landing pages), secondary, outline, ghost, danger, link. tone="prospect" paints any variant from the page\'s --lp-* properties.',
  props: [{ name: 'variant', type: "'primary'|'accent'|'secondary'|'outline'|'ghost'|'danger'|'link'", default: 'primary', description: 'Visual weight' }, { name: 'size', type: "'sm'|'md'|'lg'", default: 'md', description: '44 / 48 / 56 px' }, { name: 'tone', type: "'default'|'prospect'", default: 'default', description: 'prospect reads --lp-primary / --lp-accent / --lp-text with --color-* fallbacks' }, { name: 'icon', type: 'IconName', description: 'Leading icon' }, { name: 'loading', type: 'boolean', description: 'Spinner + disabled' }, { name: 'block', type: 'boolean', description: 'Full width' }, { name: 'ref', type: 'Ref<HTMLButtonElement>', description: 'Forwarded (ConfirmDialog focuses Cancel)' }],
  states: ['default', 'hover', 'active', 'disabled', 'loading', 'prospect'],
  usages: [{ title: 'Variants', render: () => h('div', { className: 'row wrap' }, h(Button, null, 'Open your demo'), h(Button, { variant: 'accent', iconRight: 'arrow-right' }, 'Open your demo'), h(Button, { variant: 'secondary' }, 'Book a call'), h(Button, { variant: 'outline', icon: 'filter' }, 'Filters'), h(Button, { variant: 'ghost', icon: 'plus' }, 'Add prospect'), h(Button, { variant: 'danger', icon: 'trash' }, 'Delete'), h(Button, { variant: 'link' }, 'Skip')) },
    { title: 'Sizes and states', render: () => h('div', { className: 'row wrap' }, h(Button, { size: 'sm' }, 'Small 44'), h(Button, null, 'Medium 48'), h(Button, { size: 'lg' }, 'Large 56'), h(Button, { loading: true }, 'Saving'), h(Button, { disabled: true }, 'Disabled')) },
    { title: 'tone="prospect" inside a themed root (falls back to tokens elsewhere)', render: () => h('div', { className: 'row wrap', style: { '--lp-primary': '#B3542E', '--lp-accent': '#F2C14E', '--lp-on-primary': '#fff', '--lp-on-accent': '#2B1C14', '--lp-surface': '#FFF8F2', '--lp-text': '#2B1C14', '--lp-bg': '#F4E9DF', padding: 12, background: '#F4E9DF', borderRadius: 12 } as Record<string, string | number> }, h(Button, { tone: 'prospect' }, 'Open your demo'), h(Button, { tone: 'prospect', variant: 'accent' }, 'Book a call'), h(Button, { tone: 'prospect', variant: 'secondary' }, 'Secondary'), h(Button, { tone: 'prospect', variant: 'outline' }, 'Outline'), h(Button, { tone: 'prospect', variant: 'ghost' }, 'Ghost'), h(Button, { tone: 'prospect', variant: 'link' }, 'Link')) }],
  a11y: ['Native <button>; type defaults to "button".', 'aria-busy while loading.', 'Never under 44 px tall.', 'prospect text colours come from --lp-on-primary / --lp-on-accent (readableOn() in prospectStyle), never assumed white.'], usedBy: ['HUB-01', 'D-02', 'D-07', 'L-01'] });
