import { createElement as h } from 'react';
import type { RouteDef } from '../../specs/types';
import { PLAN_ROLES, specs } from './specs';
import { KanbanPage } from './KanbanPage';
import { ListPage } from './ListPage';
import { TimelinePage } from './TimelinePage';
import { TaskPage } from './TaskPage';

export const routes: RouteDef[] = [
  { path: '/plan', element: h(KanbanPage), spec: specs.kanban, roles: PLAN_ROLES, surface: 'plan', nav: { label: 'Kanban', icon: 'kanban', order: 1, group: 'plan' } },
  { path: '/plan/list', element: h(ListPage), spec: specs.list, roles: PLAN_ROLES, surface: 'plan', nav: { label: 'List', icon: 'list', order: 2, group: 'plan' } },
  { path: '/plan/timeline', element: h(TimelinePage), spec: specs.timeline, roles: PLAN_ROLES, surface: 'plan', nav: { label: 'Timeline', icon: 'chart', order: 3, group: 'plan' } },
  { path: '/plan/tasks/:id', element: h(TaskPage), spec: specs.task, roles: PLAN_ROLES, surface: 'plan' },
];

export const strings = {
  'plan.k01_title': { en: 'Plan Kanban', es: 'Kanban del plan' },
  'plan.k02_title': { en: 'Plan list', es: 'Lista del plan' },
  'plan.k03_title': { en: 'Plan timeline', es: 'Línea de dependencias' },
  'plan.tagline': { en: 'Tasks are bound by dependencies, not calendar days.', es: 'Las tareas se ordenan por dependencias, no por días del calendario.' },
  'plan.views': { en: 'Plan views', es: 'Vistas del plan' },
  'plan.view_kanban': { en: 'Kanban', es: 'Kanban' }, 'plan.view_list': { en: 'List', es: 'Lista' }, 'plan.view_timeline': { en: 'Timeline', es: 'Línea de dependencias' },
  'plan.filters': { en: 'Filters', es: 'Filtros' }, 'plan.all': { en: 'all', es: 'todo' },
  'plan.phase': { en: 'Phase', es: 'Fase' }, 'plan.phase_n': { en: 'Phase {n}', es: 'Fase {n}' }, 'plan.phase_tasks': { en: '{n} tasks', es: '{n} tareas' },
  'plan.model': { en: 'Model', es: 'Modelo' }, 'plan.status': { en: 'Status', es: 'Estado' },
  'plan.tasks': { en: 'Tasks', es: 'Tareas' }, 'plan.shown': { en: 'Shown', es: 'Mostradas' }, 'plan.done': { en: 'Done', es: 'Hechas' },
  'plan.progress': { en: 'Plan progress', es: 'Avance del plan' },
  'plan.ready': { en: 'Ready', es: 'Listas' }, 'plan.ready_hint': { en: 'every dependency done', es: 'todas las dependencias hechas' },
  'plan.ready_only': { en: 'ready only', es: 'solo listas' }, 'plan.ready_yes': { en: 'ready', es: 'lista' }, 'plan.ready_no': { en: 'waiting', es: 'esperando' },
  'plan.waiting': { en: 'Waiting', es: 'En espera' }, 'plan.waiting_hint': { en: 'blocked or awaiting Justin', es: 'bloqueadas o esperando a Justin' },
  'plan.lane_backlog': { en: 'Backlog', es: 'Pendiente' }, 'plan.lane_doing': { en: 'Doing', es: 'En curso' }, 'plan.lane_done': { en: 'Done', es: 'Hecho' },
  'plan.lane_blocked': { en: 'Blocked', es: 'Bloqueado' }, 'plan.lane_awaiting_justin': { en: 'Awaiting Justin', es: 'Esperando a Justin' },
  'plan.empty_lane': { en: 'Nothing in this lane', es: 'Nada en esta columna' },
  'plan.empty_title': { en: 'No task matches these filters', es: 'Ninguna tarea coincide con estos filtros' }, 'plan.empty_body': { en: 'Clear a filter to see the rest of the plan.', es: 'Quita un filtro para ver el resto del plan.' },
  'plan.deps': { en: '{done}/{total} deps done', es: '{done}/{total} dependencias hechas' },
  'plan.deps_none': { en: 'no dependencies', es: 'sin dependencias' },
  'plan.deps_all_done': { en: 'All dependencies done: {list}', es: 'Todas las dependencias hechas: {list}' },
  'plan.deps_waiting': { en: 'Still waiting on {list}', es: 'Todavía espera a {list}' },
  'plan.direct_deps': { en: '{n} direct dependencies · {d} direct dependents', es: '{n} dependencias directas · {d} dependientes directas' },
  'plan.move_prev': { en: 'Move to the previous lane', es: 'Mover a la columna anterior' }, 'plan.move_next': { en: 'Move to the next lane', es: 'Mover a la columna siguiente' },
  'plan.set_status': { en: 'Status', es: 'Estado' }, 'plan.set_status_for': { en: 'Status of {id}', es: 'Estado de {id}' },
  'plan.moved': { en: '{id} moved to {status}', es: '{id} movida a {status}' },
  'plan.rule_blocked': { en: 'Blocked by a rule', es: 'Bloqueado por una regla' },
  'plan.rule_blocked_body': { en: '{rule}: nothing is done while a dependency is open. Still waiting on {deps}.', es: '{rule}: nada está hecho mientras una dependencia siga abierta. Todavía espera a {deps}.' },
  'plan.rule_ok': { en: 'R-K01: every dependency is done, so this can move to done.', es: 'R-K01: todas las dependencias están hechas, puede pasar a hecho.' },
  'plan.rule_hint': { en: 'R-K01: cannot be done while {deps} is open.', es: 'R-K01: no puede estar hecha mientras {deps} siga abierta.' },
  'plan.readonly': { en: 'Read-only', es: 'Solo lectura' }, 'plan.readonly_body': { en: 'Moving a task needs the plan.edit permission; you are viewing the plan.', es: 'Mover una tarea requiere el permiso plan.edit; estás viendo el plan.' },
  'plan.sync_docs': { en: 'Sync to build-plan.md', es: 'Sincronizar con build-plan.md' },
  'plan.sync_docs_will': { en: 'write the lanes back into docs/build-plan.md and the kanban doc', es: 'escribir las columnas en docs/build-plan.md y el kanban' },
  'plan.clear_filters': { en: 'Clear filters and sort', es: 'Limpiar filtros y orden' },
  'plan.sort': { en: 'Sort', es: 'Orden' }, 'plan.asc': { en: 'ascending', es: 'ascendente' }, 'plan.desc': { en: 'descending', es: 'descendente' },
  'plan.col_id': { en: 'Id', es: 'Id' }, 'plan.col_title': { en: 'Title', es: 'Título' }, 'plan.col_module': { en: 'Module', es: 'Módulo' }, 'plan.col_codes': { en: 'Codes', es: 'Códigos' },
  'plan.col_model': { en: 'Model', es: 'Modelo' }, 'plan.col_phase': { en: 'Phase', es: 'Fase' }, 'plan.col_depends': { en: 'Depends on', es: 'Depende de' },
  'plan.col_status': { en: 'Status', es: 'Estado' }, 'plan.col_owner': { en: 'Owner', es: 'Responsable' },
  'plan.list_hint': { en: 'Click a row (or its id) to open the task. Under 768 px every row becomes a labelled card.', es: 'Haz clic en una fila (o su id) para abrir la tarea. Bajo 768 px cada fila se vuelve una tarjeta.' },
  'plan.critical_path': { en: 'Critical path', es: 'Ruta crítica' },
  'plan.critical_path_hint': { en: 'longest dependency chain: {path}', es: 'cadena de dependencias más larga: {path}' },
  'plan.edges': { en: 'Dependencies', es: 'Dependencias' }, 'plan.edges_hint': { en: 'arrows in the graph', es: 'flechas en el grafo' },
  'plan.graph_label': { en: 'Dependency graph. Zoom with the plus and minus keys, Escape clears the focus.', es: 'Grafo de dependencias. Zoom con las teclas más y menos, Escape quita el foco.' },
  'plan.graph_aria': { en: 'Dependency graph with {nodes} tasks and {edges} dependencies, laid out by phase.', es: 'Grafo de dependencias con {nodes} tareas y {edges} dependencias, por fase.' },
  'plan.graph_hint': { en: 'Tab to a task and press Enter to focus it (upstream and downstream light up). + / - zoom, 0 resets, Escape clears. The graph scrolls sideways inside its own frame.', es: 'Tabula a una tarea y pulsa Enter para enfocarla (se iluminan sus dependencias y dependientes). + / - para zoom, 0 reinicia, Escape quita el foco. El grafo se desplaza dentro de su marco.' },
  'plan.node_aria': { en: '{id}: {title}. Status {status}, model {model}, phase {phase}, {deps} dependencies, {ready}.', es: '{id}: {title}. Estado {status}, modelo {model}, fase {phase}, {deps} dependencias, {ready}.' },
  'plan.focus_pick': { en: 'Focus a task', es: 'Enfocar una tarea' }, 'plan.focus_none': { en: 'Focus a task…', es: 'Enfocar una tarea…' },
  'plan.focus_critical': { en: 'Critical path', es: 'Ruta crítica' }, 'plan.clear_focus': { en: 'Clear focus', es: 'Quitar foco' },
  'plan.focus_filtered': { en: 'The focused task is hidden by the current filters; its neighbours still light up where they are shown.', es: 'La tarea enfocada está oculta por los filtros; sus vecinas se iluminan donde se muestran.' },
  'plan.zoom_in': { en: 'Zoom in', es: 'Acercar' }, 'plan.zoom_out': { en: 'Zoom out', es: 'Alejar' }, 'plan.zoom_reset': { en: 'Reset zoom', es: 'Reiniciar zoom' },
  'plan.legend': { en: 'Legend', es: 'Leyenda' }, 'plan.legend_edge': { en: 'arrow = depends on', es: 'flecha = depende de' },
  'plan.waits_on': { en: 'Waits on', es: 'Espera a' }, 'plan.blocks': { en: 'Blocks', es: 'Bloquea a' }, 'plan.blocks_none': { en: 'nothing waits on this', es: 'nada espera a esta' },
  'plan.notes': { en: 'Notes', es: 'Notas' }, 'plan.no_notes': { en: 'No notes on this task.', es: 'Sin notas en esta tarea.' },
  'plan.rules': { en: 'Rules', es: 'Reglas' }, 'plan.done_at': { en: 'Done at', es: 'Hecha el' }, 'plan.updated_at': { en: 'Updated', es: 'Actualizada' },
  'plan.unknown_dep': { en: 'unknown task', es: 'tarea desconocida' },
  'plan.open_task': { en: 'Open task', es: 'Abrir tarea' }, 'plan.see_in_graph': { en: 'See it in the graph', es: 'Verla en el grafo' }, 'plan.back_to_kanban': { en: 'Back to the Kanban', es: 'Volver al Kanban' },
  'plan.not_found': { en: 'No task with id {id}', es: 'No hay tarea con id {id}' }, 'plan.not_found_body': { en: 'The plan is seeded from docs/build-plan.md; open the Kanban to pick a task.', es: 'El plan viene de docs/build-plan.md; abre el Kanban para elegir una tarea.' },
};
