import { createElement as h } from 'react';
import type { RouteDef } from '../../specs/types';
import { MANUAL_ROLES, specs } from './specs';
import { ManualHome } from './ManualHome';
import { ChapterPage } from './ChapterPage';

const chapter = (path: string, code: string, label: string, icon: string, order: number): RouteDef => ({
  path, element: h(ChapterPage, { code }), spec: specs[code === 'M-02' ? 'intake' : code === 'M-03' ? 'compose' : code === 'M-04' ? 'outreach' : 'calls'],
  roles: MANUAL_ROLES, surface: 'manual', nav: { label, icon, order, group: 'manual' },
});

export const routes: RouteDef[] = [
  { path: '/manual', element: h(ManualHome), spec: specs.home, roles: MANUAL_ROLES, surface: 'manual', nav: { label: 'Manual', icon: 'book', order: 1, group: 'manual' } },
  chapter('/manual/intake', 'M-02', 'Intake', 'sparkles', 2),
  chapter('/manual/compose', 'M-03', 'Compose & publish', 'wand', 3),
  chapter('/manual/outreach', 'M-04', 'Outreach', 'mail', 4),
  chapter('/manual/calls', 'M-05', 'Walkthrough calls', 'phone', 5),
];

/** EN + ES. Chapter prose lives in docs/ops-manual/<lang>/; these are the reader's own strings. */
export const strings = {
  'manual.loading': { en: 'Loading the chapter…', es: 'Cargando el capítulo…' },
  'manual.missing': { en: 'No chapter file for {slug}', es: 'No hay archivo de capítulo para {slug}' },
  'manual.missing_body': { en: 'Chapters live in docs/ops-manual/en and docs/ops-manual/es with the same filename. Add the file and it appears here.', es: 'Los capítulos viven en docs/ops-manual/en y docs/ops-manual/es con el mismo nombre de archivo. Agrega el archivo y aparece aquí.' },
  'manual.chapter_nav': { en: 'Chapters', es: 'Capítulos' },
  'manual.jump': { en: 'Jump to a chapter', es: 'Ir a un capítulo' },
  'manual.prev': { en: 'Previous', es: 'Anterior' }, 'manual.next': { en: 'Next', es: 'Siguiente' },
  'manual.print': { en: 'Print', es: 'Imprimir' },
  'manual.lang_hint': { en: 'EN / ES follows the toggle in the header', es: 'EN / ES sigue el interruptor de la cabecera' },
  'manual.part': { en: 'Part {part}', es: 'Parte {part}' },
  'manual.for_role': { en: 'For {role}', es: 'Para {role}' },
  'manual.version': { en: 'version {version}', es: 'versión {version}' },
  'manual.updated': { en: 'updated {updated}', es: 'actualizado {updated}' },
  'manual.missing_keys': { en: 'front matter missing: {keys}', es: 'faltan claves de encabezado: {keys}' },
  'manual.no_translation': { en: 'English fallback', es: 'Se muestra en inglés' },
  'manual.chapters': { en: 'Chapters', es: 'Capítulos' },
  'manual.open_decisions': { en: 'Open decisions', es: 'Decisiones pendientes' },
  'manual.open_decisions_hint': { en: 'Collected from every chapter. These need Justin before the manual can say what happens.', es: 'Recogidas de todos los capítulos. Necesitan a Justin antes de que el manual pueda decir qué pasa.' },
  'manual.no_decisions': { en: 'Nothing waiting on a decision', es: 'Nada esperando una decisión' },
  'manual.no_decisions_body': { en: 'Write "> DECISION NEEDED: …" in a chapter and it appears here.', es: 'Escribe "> DECISION NEEDED: …" en un capítulo y aparece aquí.' },
  'manual.decision_needed': { en: 'Decision needed', es: 'Decisión pendiente' },
  'manual.health': { en: 'Manual health', es: 'Estado del manual' },
  'manual.stat_translated': { en: 'Translated', es: 'Traducidos' },
  'manual.stat_frontmatter': { en: 'Front matter complete', es: 'Encabezado completo' },
  'manual.stat_frontmatter_hint': { en: 'title, role, part, version, updated, summary', es: 'title, role, part, version, updated, summary' },
  'manual.stat_decisions': { en: 'Open decisions', es: 'Decisiones pendientes' },
  'manual.rule_m02': { en: 'R-M02: every chapter has a Spanish mirror', es: 'R-M02: cada capítulo tiene su espejo en español' },
  'manual.gaps': { en: 'Missing a translation: {list}', es: 'Falta traducción: {list}' },
  'manual.unrouted': { en: 'Chapter files with no route yet: {list}', es: 'Archivos de capítulo sin ruta todavía: {list}' },
  'manual.whole_manual': { en: 'The whole manual', es: 'El manual completo' },
  'manual.this_chapter': { en: 'Chapter I', es: 'Capítulo I' },
  'manual.read_all': { en: 'Read the whole manual', es: 'Leer el manual completo' },
  'manual.read_one': { en: 'Just this chapter', es: 'Solo este capítulo' },
  // live blocks (R-M01)
  'manual.live_now': { en: 'live from the running app', es: 'en vivo desde la aplicación' },
  'manual.unknown_directive': { en: 'Unknown live-data directive {raw}. See docs/ops-manual/README.md for the list.', es: 'Directiva de datos en vivo desconocida {raw}. Consulta docs/ops-manual/README.md.' },
  'manual.block_stats': { en: 'The product, counted', es: 'El producto, en números' },
  'manual.block_routes': { en: 'Routes on the {surface} surface', es: 'Rutas de la superficie {surface}' },
  'manual.no_routes': { en: 'No routes on the {surface} surface', es: 'No hay rutas en la superficie {surface}' },
  'manual.block_roles': { en: 'Roles and permissions', es: 'Roles y permisos' },
  'manual.block_prospects': { en: 'Seeded prospects', es: 'Prospectos de demostración' },
  'manual.no_prospects': { en: 'No prospects in this browser yet', es: 'Todavía no hay prospectos en este navegador' },
  'manual.block_archetypes': { en: 'Archetypes scored for the seeded prospects', es: 'Arquetipos puntuados para los prospectos de demostración' },
  'manual.block_pricebands': { en: 'Price bands', es: 'Bandas de precio' },
  'manual.block_channels': { en: 'Outreach channels', es: 'Canales de contacto' },
  'manual.block_kpi': { en: 'Live numbers: {which}', es: 'Números en vivo: {which}' },
  'manual.no_kpi': { en: 'No KPI called {which}', es: 'No existe el indicador {which}' },
  'manual.stat_routes': { en: 'Routes', es: 'Rutas' }, 'manual.stat_built': { en: 'Built', es: 'Construidas' }, 'manual.stat_stubs': { en: 'Stubs', es: 'Pendientes' },
  'manual.stat_tables': { en: 'Tables', es: 'Tablas' }, 'manual.stat_rules': { en: 'Rules', es: 'Reglas' }, 'manual.stat_components': { en: 'Components', es: 'Componentes' },
  'manual.stat_chapters': { en: 'Chapters', es: 'Capítulos' },
  'manual.col_code': { en: 'Code', es: 'Código' }, 'manual.col_page': { en: 'Page', es: 'Página' }, 'manual.col_route': { en: 'Route', es: 'Ruta' },
  'manual.col_status': { en: 'Status', es: 'Estado' }, 'manual.col_actions': { en: 'Actions', es: 'Acciones' },
  'manual.built': { en: 'built', es: 'construida' }, 'manual.stub': { en: 'stub', es: 'pendiente' },
  'manual.col_role': { en: 'Role', es: 'Rol' }, 'manual.col_key': { en: 'Key', es: 'Clave' }, 'manual.col_perms': { en: 'Permissions', es: 'Permisos' }, 'manual.col_sample': { en: 'For example', es: 'Por ejemplo' },
  'manual.col_business': { en: 'Business', es: 'Negocio' }, 'manual.col_who': { en: 'Who', es: 'Quién' }, 'manual.col_city': { en: 'City', es: 'Ciudad' },
  'manual.col_team': { en: 'Team / sites', es: 'Equipo / sedes' }, 'manual.col_warmth': { en: 'Warmth', es: 'Temperatura' },
  'manual.col_confidence': { en: 'Confidence', es: 'Confianza' }, 'manual.col_live_page': { en: 'Live page', es: 'Página en vivo' },
  'manual.col_archetype': { en: 'Archetype', es: 'Arquetipo' }, 'manual.col_top_score': { en: 'Top score', es: 'Puntuación máxima' },
  'manual.col_wins': { en: 'Wins for', es: 'Gana con' }, 'manual.col_reason': { en: 'Leading reason', es: 'Razón principal' },
  'manual.col_band': { en: 'Band', es: 'Banda' }, 'manual.col_when': { en: 'When', es: 'Cuándo' }, 'manual.col_monthly': { en: 'Per month', es: 'Al mes' },
  'manual.col_yearly': { en: 'Per year', es: 'Al año' }, 'manual.col_who_band': { en: 'Seeded prospects', es: 'Prospectos de demostración' },
  'manual.band_starter': { en: '5 or fewer people, one location', es: '5 personas o menos, una sede' },
  'manual.band_team': { en: '6 to 25 people, one location', es: 'De 6 a 25 personas, una sede' },
  'manual.band_multi': { en: 'More than 25 people, or more than one location', es: 'Más de 25 personas, o más de una sede' },
  'manual.col_channel': { en: 'Channel', es: 'Canal' }, 'manual.col_drafts': { en: 'Drafts', es: 'Borradores' }, 'manual.col_sent': { en: 'Sent', es: 'Enviados' },
  'manual.col_opened': { en: 'Opened', es: 'Abiertos' }, 'manual.col_clicked': { en: 'Clicked', es: 'Con clic' },
  'manual.kpi_prospects': { en: 'Prospects', es: 'Prospectos' }, 'manual.kpi_avg_confidence': { en: 'Average confidence', es: 'Confianza media' },
  'manual.kpi_publishable': { en: 'Past the gate', es: 'Pasan la puerta' }, 'manual.kpi_publishable_hint': { en: 'R-S01: 30 % confidence to publish', es: 'R-S01: 30 % de confianza para publicar' },
  'manual.kpi_avg_savings': { en: 'Average net saving', es: 'Ahorro neto medio' }, 'manual.kpi_avg_savings_hint': { en: 'per year, after our price', es: 'al año, después de nuestro precio' },
  'manual.kpi_touches': { en: 'Touches', es: 'Contactos' }, 'manual.kpi_sent': { en: 'Sent', es: 'Enviados' },
  'manual.kpi_open_rate': { en: 'Open rate', es: 'Tasa de apertura' }, 'manual.kpi_click_rate': { en: 'Click rate', es: 'Tasa de clic' },
  'manual.kpi_bookings': { en: 'Bookings', es: 'Reservas' }, 'manual.kpi_confirmed': { en: 'Confirmed', es: 'Confirmadas' },
  'manual.kpi_avg_minutes': { en: 'Average length', es: 'Duración media' }, 'manual.kpi_avg_minutes_hint': { en: 'minutes booked', es: 'minutos reservados' },
  'manual.kpi_live_pages': { en: 'Live pages', es: 'Páginas en vivo' },
  'manual.kpi_views': { en: 'Page views', es: 'Vistas de página' }, 'manual.kpi_cta': { en: 'CTA clicks', es: 'Clics en el CTA' },
  'manual.kpi_demo': { en: 'Demo opens', es: 'Aperturas de la demo' }, 'manual.kpi_booked': { en: 'Booked', es: 'Reservadas' },
  'manual.figure_alt': { en: 'Screenshot of {code}: {caption}', es: 'Captura de {code}: {caption}' },
  'manual.figure_missing': { en: 'Screenshot not captured yet', es: 'Captura todavía no tomada' },
};
