import { defineSpec } from '../../specs/types';
import { EVERYONE } from '../../auth/roles';
export const hubSpec = defineSpec({
  code: 'HUB-01', name: 'Testing hub', purpose: 'Start here: switch language, theme, dev mode and role; open every surface (prospect landing pages, OS demo live in a phone, studio, analytics, plan, proposal, website, docs, manual, dev tools) and see the build counts.',
  layout: ['header (brand, EN/ES, theme, dev mode, Commands + Speak)', 'role switcher', 'prospects: landing pages per archetype + demo', 'OS demo in PhoneFrame', 'surface cards', 'dev tools D-01..D-09', 'counts footer'],
  data: ['prospects', 'pages', 'tasks', 'feedback'], roles: EVERYONE, logic: ['counts = routes / built / stubs / tables / rules / components from registries', 'prospect cards read live pages and the savings from the composed model', 'Commands / Speak open the CommandPalette (also Ctrl/Cmd+K on every shell); a spoken or typed phrase is ranked by src/a11y/voice.ts matchPhrase over window.__leadmagnet.vocabulary and run through runAction'], integrations: [],
  components: ['LangToggle', 'IconButton', 'Toggle', 'RoleSwitcher', 'PhoneFrame', 'Card', 'Badge', 'Stat', 'Button', 'Avatar', 'DeviceMockup', 'CommandPalette'],
  actions: [{ id: 'hub.setLang', label: 'EN / ES', intent: 'switch language to {lang}', params: { lang: 'enum:en|es' } }, { id: 'hub.toggleTheme', label: 'Theme', intent: 'switch to dark mode' }, { id: 'hub.toggleDevMode', label: 'Dev mode', intent: 'turn dev mode on', permission: 'dev.tools' }, { id: 'hub.switchUser', label: 'Sign in as', intent: 'sign in as {role}', params: { role: 'string' } }, { id: 'hub.openSurface', label: 'Open', intent: 'open {surface}', params: { surface: 'string' } }, { id: 'hub.resetDemoData', label: 'Reset demo data', intent: 'reset the demo database', permission: 'dev.tools' }, { id: 'hub.openCommands', label: 'Commands', intent: 'open the command palette' }, { id: 'hub.voiceListen', label: 'Speak', intent: 'listen for a voice command' }],
  rules: ['R-P01', 'R-P02'], states: ['default', 'dev mode', 'viewing as'], checkedAt: [390, 1280],
});
export const noAccessSpec = defineSpec({ code: 'HUB-02', name: 'No access', purpose: 'Friendly page when the current role cannot open a route; offers the hub and the roles that can.', layout: ['message', 'roles that can', 'hub link'], data: [], roles: EVERYONE, logic: ['reads ?from= and lists roles allowed on that route'], integrations: [], components: ['Card', 'Button', 'Badge'], actions: [{ id: 'hub.signInAs', label: 'Sign in as', intent: 'sign in as {role}', params: { role: 'string' } }], states: ['default'], checkedAt: [390, 1280] });
