import { createElement as h } from 'react';
import { defineMeta } from '../../../design/meta';
import { Stat } from './Stat';
export default defineMeta({ tier: 'molecule', name: 'Stat', description: 'KPI tile for dashboards, hub footer, role views and landing savings: label, value, delta (arrow + signed number + colour), sparkline, hint, estimate badge.',
  props: [{ name: 'label', type: 'string', required: true, description: '' }, { name: 'value', type: 'ReactNode', required: true, description: '' }, { name: 'hint', type: 'ReactNode', description: 'Was string; any node' }, { name: 'tone', type: "'default'|'success'|'warn'|'danger'|'accent'|'prospect'", default: 'default', description: 'prospect reads --lp-* with --color-* fallbacks' }, { name: 'size', type: "'sm'|'md'|'lg'", default: 'md', description: '' }, { name: 'align', type: "'start'|'center'|'end'", default: 'start', description: '' }, { name: 'delta', type: '{ value: number; label?; direction?: up|down|flat; good?: up|down; format? }', description: 'Direction from the sign unless given; `good` says which way is success (down for costs)' }, { name: 'spark', type: 'number[]', description: 'Inline sparkline, aria-hidden + sr-only "first -> last"' }, { name: 'sparkLabel', type: 'string', description: 'Text alternative for the sparkline' }, { name: 'estimate', type: 'string', description: 'Dashed tile + this badge text ("estimate" / "propuesto")' }],
  states: ['default', 'delta good / bad / flat', 'estimate', 'sm / lg', 'prospect'],
  usages: [{ title: 'Row', render: () => h('div', { className: 'grid grid-4' }, h(Stat, { label: 'Routes', value: 58 }), h(Stat, { label: 'Built', value: 11, tone: 'success' }), h(Stat, { label: 'Stubs', value: 47, tone: 'warn' }), h(Stat, { label: 'Savings / yr', value: '$18,400', tone: 'accent', hint: 'Paws & Play' })) },
    { title: 'Delta, sparkline, estimate, hint node', render: () => h('div', { className: 'grid grid-4' }, h(Stat, { label: 'Page views', value: 1284, delta: { value: 12, label: 'vs last 30 days' }, spark: [3, 5, 4, 8, 9, 7, 12, 14] }), h(Stat, { label: 'Cost / mo', value: '$1,240', delta: { value: -90, good: 'down', label: 'after the audit', format: (v) => `${v < 0 ? '-' : '+'}$${Math.abs(v)}` }, spark: [1420, 1400, 1380, 1330, 1240] }), h(Stat, { label: 'Bookings', value: 6, delta: { value: -2, label: 'vs last week' }, tone: 'warn' }), h(Stat, { label: 'Net / yr', value: '$18,400', estimate: 'estimate', delta: { value: 0, label: 'flat' }, hint: h('a', { href: '#/dev/components' }, 'how we count') })) },
    { title: 'Sizes and align', render: () => h('div', { className: 'grid grid-3' }, h(Stat, { size: 'sm', label: 'Small', value: 42, delta: { value: 3 } }), h(Stat, { label: 'Centered', value: '73 %', align: 'center', spark: [40, 55, 61, 73] }), h(Stat, { size: 'lg', label: 'Large, end', value: '$2.1k', align: 'end' })) },
    { title: 'tone="prospect" (inherits --lp-* when set on an ancestor)', render: () => h('div', { className: 'grid grid-2', style: { '--lp-primary': '#B3542E', '--lp-surface': '#FFF8F2', '--lp-text': '#2B1C14', '--lp-bg': '#F4E9DF' } as Record<string, string> }, h(Stat, { tone: 'prospect', label: 'Saved per year', value: '$18,400', spark: [2, 4, 6, 9] }), h(Stat, { tone: 'prospect', label: 'Tools cut', value: 6, delta: { value: -6, good: 'down', label: 'from 9 to 3' } })) }],
  a11y: ['Label precedes value in DOM order.', 'Delta is arrow + signed number + optional label; colour only reinforces.', 'Sparkline SVG is aria-hidden; a sr-only span says first -> last (or sparkLabel).'], usedBy: ['HUB-01', 'D-01', 'D-02', 'A-03', 'L-02'] });
