import { createElement as h } from 'react';
import { Link } from 'react-router-dom';
import { defineMeta } from '../../../design/meta';
import { Placeholder } from './Placeholder';
import { Button } from '../Button/Button';
export default defineMeta({ tier: 'atom', name: 'Placeholder', description: 'P-09: any control that does not work yet. Tooltip on hover and focus, toast on activation, dashed outline + badge in dev mode, data-placeholder attribute. Wraps buttons and links (navigation is cancelled).',
  props: [{ name: 'will', type: 'string', required: true, description: 'What it will do' }, { name: 'by', type: 'string', description: 'Module / task that ships it' }, { name: 'children', type: 'ReactElement', description: 'Element to wrap: Button, Link, <a> (its onClick is replaced; a link never navigates)' }, { name: 'button', type: 'ButtonProps & { label }', description: 'Render a Button when no children' }, { name: 'block', type: 'boolean', description: 'Full width' }], states: ['default', 'hover/focus tooltip', 'dev mode badge', 'wrapped link'],
  usages: [{ title: 'Wrapping a button', render: () => h('div', { className: 'row wrap' }, h(Placeholder, { will: 'generate hero image with the image provider', by: 'T40' }, h(Button, { variant: 'accent', icon: 'image' }, 'Generate images')), h(Placeholder, { will: 'send this outreach email', by: 'studio', button: { label: 'Send', variant: 'outline' } })) },
    { title: 'Wrapping a Link / anchor (stays a focusable link, activation shows the toast, no navigation)', render: () => h('div', { className: 'row wrap' }, h(Placeholder, { will: 'open the billing portal', by: 'T43 Stripe' }, h(Link, { to: '/billing' }, 'Billing portal')), h(Placeholder, { will: 'download the signed proposal PDF', by: 'T50' }, h('a', { href: '#/proposal/pro_maya.pdf' }, 'Download PDF')), h(Placeholder, { will: 'open the live page analytics', by: 'admin' }, h(Link, { to: '/admin/analytics' }, h(Button, { variant: 'outline', icon: 'chart' }, 'Analytics')))) }],
  a11y: ['Tooltip is role=tooltip and linked via aria-describedby; shows on focus as well as hover.', 'Activation gives feedback (toast), never silence.', 'A wrapped link keeps its href and role; Enter / click / Space all show the toast and preventDefault + stopPropagation cancel navigation and row links.'], usedBy: ['HUB-01', 'D-01', 'D-02'] });
