import { createElement as h, useState } from 'react';
import { defineMeta } from '../../../design/meta';
import { DataTable, type SortState } from './DataTable';
import { Badge } from '../../atom/Badge/Badge';
import { Button } from '../../atom/Button/Button';
type R = { id: string; tool: string; cost: number; status: string };
const rows: R[] = [{ id: '1', tool: 'Toast POS', cost: 495, status: 'guessed' }, { id: '2', tool: '7shifts', cost: 105, status: 'confirmed' }, { id: '3', tool: 'QuickBooks Online', cost: 90, status: 'rejected' }];
const statusBadge = (r: R) => h(Badge, { tone: r.status === 'confirmed' ? 'success' : r.status === 'rejected' ? 'danger' : 'neutral' }, r.status);
function Controlled() {
  const [sort, setSort] = useState<SortState>({ key: 'cost', dir: 'desc' });
  return h('div', { className: 'stack-sm' }, h('code', { className: 'xs' }, `sort = ${JSON.stringify(sort)} (controlled: the page orders rows, or passes clientSort)`), h(DataTable<R>, { caption: 'Controlled sort', rows, sort, onSort: setSort, clientSort: true, dense: true, columns: [{ key: 'tool', header: 'Tool', sortable: true }, { key: 'cost', header: '$ / mo', align: 'right', sortable: true }, { key: 'status', header: 'Status', sortable: true, accessor: (r) => ['confirmed', 'guessed', 'rejected'].indexOf(r.status), render: statusBadge }] }));
}
export default defineMeta({ tier: 'organism', name: 'DataTable', description: 'The one table: real <table> with caption, sticky head, zebra rows, sortable headers (aria-sort), sr-only action headers; rows become labelled cards under 768 px.',
  props: [{ name: 'columns', type: 'Column<T>[]', required: true, description: 'key, header, render?, width?, align?, hideOnCard?, sortable?, accessor?, srOnlyHeader?' }, { name: 'rows', type: 'T[]', required: true, description: '' }, { name: 'caption', type: 'string', required: true, description: 'sr-only caption' }, { name: 'rowHref', type: '(row) => string', description: 'First cell becomes a 44 px link whose overlay covers the row (D-088)' }, { name: 'onRowClick', type: '(row) => void', description: '' }, { name: 'sort', type: '{ key, dir: asc|desc }', description: 'Controlled sort; the parent orders rows unless clientSort' }, { name: 'onSort', type: '(sort) => void', description: 'Header activation: same key toggles, new key starts asc' }, { name: 'defaultSort', type: 'SortState', description: 'Uncontrolled initial sort; the table sorts client-side by accessor ?? row[key]' }, { name: 'clientSort', type: 'boolean', description: 'Sort client-side even when controlled' }, { name: 'dense', type: 'boolean', description: '36 px rows' }, { name: 'empty', type: '{ title, body? }', description: 'EmptyState copy' }],
  states: ['default', 'empty', 'sorted asc / desc', 'cards < 768'],
  usages: [{ title: 'Uncontrolled sort (click a header) + sr-only action column', render: () => h(DataTable<R>, { caption: 'Stack guesses', rows, defaultSort: { key: 'tool', dir: 'asc' }, columns: [{ key: 'tool', header: 'Tool', sortable: true }, { key: 'cost', header: '$ / mo', align: 'right', sortable: true }, { key: 'status', header: 'Status', render: statusBadge }, { key: 'actions', header: 'Actions', srOnlyHeader: true, align: 'right', render: (r) => h(Button, { size: 'sm', variant: 'outline', 'aria-label': `Confirm ${r.tool}` }, 'Confirm') }] }) },
    { title: 'Controlled sort with a custom accessor', render: () => h(Controlled) }],
  a11y: ['Semantic table with caption and th scope.', 'A sortable header is one 44 px button filling the th; aria-sort on the active th says ascending / descending, the glyph is aria-hidden.', 'srOnlyHeader keeps the header text for screen readers and card labels (button columns are labelled).', 'Card mode keeps header text as labels; sorting is not offered in card mode yet (headers are hidden).'], usedBy: ['D-01', 'D-02', 'D-03', 'D-04', 'D-09', 'K-02'] });
