// Generates supabase/schema.sql and docs/data-model.md from src/data/schema/*.ts. Run: npm run sql. Commit both outputs.
import { readdirSync, writeFileSync, mkdirSync } from 'node:fs';
globalThis.import_meta_env_shim = true;
const dir = new URL('../src/data/schema/', import.meta.url);
const { TABLE_GROUPS, baseColumns } = await import('../src/data/schema/types.ts');
const tables = [];
for (const f of readdirSync(dir).filter((f) => f.endsWith('.ts') && !['index.ts', 'types.ts'].includes(f)).sort()) { const m = await import(new URL(f, dir)); if (m.tables) tables.push(...m.tables); }
tables.sort((a, b) => a.name.localeCompare(b.name));
const PG = { uuid: 'uuid', text: 'text', int: 'integer', numeric: 'numeric(12,2)', money: 'numeric(12,2)', bool: 'boolean', timestamptz: 'timestamptz', date: 'date', json: 'jsonb', enum: 'text' };
const col = (c) => { const parts = [`  ${c.name} ${PG[c.type]}`]; if (c.name === 'id') parts.push('primary key default gen_random_uuid()'); else if (!c.nullable) parts.push('not null'); if (c.name === 'created_at' || c.name === 'updated_at') parts.push('default now()'); if (c.type === 'bool') parts.push('default false'); if (c.enum) parts.push(`check (${c.name} in (${c.enum.map((e) => `'${e}'`).join(', ')}))`); if (c.references) parts.push(`references public.${c.references}(id) on delete set null`); const line = parts.join(' '); return c.description ? `  -- ${c.description}\n${line}` : line; };
let sql = `-- Lead Magnet - Postgres schema draft (Supabase later, T44)\n-- GENERATED from src/data/schema/*.ts by scripts/gen-sql.mjs. Edit the TS, regenerate, review, then apply as a migration.\n-- Conventions: every table has id, created_at, updated_at.\n\ncreate extension if not exists pgcrypto;\n\ncreate or replace function public.touch_updated_at() returns trigger language plpgsql as $$\nbegin new.updated_at = now(); return new; end $$;\n\n`;
for (const t of tables) { const cols = [...baseColumns(t), ...t.columns].map(col); const access = (t.access ?? []).map((n) => `--   · ${n}`).join('\n'); sql += `-- ${t.group} · ${t.label}: ${t.description}\n${access ? `-- access:\n${access}\n` : ''}create table if not exists public.${t.name} (\n${cols.join(',\n')}\n);\n`; for (const c of t.columns.filter((c) => c.references)) sql += `create index if not exists ${t.name}_${c.name}_idx on public.${t.name}(${c.name});\n`; sql += `create trigger ${t.name}_touch before update on public.${t.name} for each row execute function public.touch_updated_at();\n\n`; }
sql += `-- Access intent per role (RLS later):\n--   super_admin        everything\n--   strategist         prospects, stack_guesses, pages, assets, touches, bookings read/write; events read\n--   analyst            read events, pages, prospects, bookings, touches\n--   prospect           read own page / prospect through the public slug; insert events, bookings, feedback\n--   guest              insert events, bookings\n`;
mkdirSync(new URL('../supabase/', import.meta.url), { recursive: true });
writeFileSync(new URL('../supabase/schema.sql', import.meta.url), sql);
let md = `# Data model\n\n_Generated from \`src/data/schema/*.ts\` by \`npm run sql\`. The TypeScript files are the source of truth; \`supabase/schema.sql\` is the Postgres draft; this page is the human view. Browse live rows at \`/#/dev/tables\` (D-03)._\n\n## Principles\n- **Same interface, two providers.** Pages call \`useData()\` / \`useTable()\` / \`useRow()\` (\`DataProvider\`: list, get, insert, update, remove, subscribe). \`MockProvider\` (localStorage \`leadmagnet.db.v1\`) today; \`SupabaseProvider\` later (T44). Swap is one line in \`src/data/DataContext.tsx\`.\n- **Every table has \`id, created_at, updated_at\`.** Writes go by id through the provider; lists re-render from \`subscribe\` (multiplayer-ready, P-14).\n- **The engine is pure.** \`stack_guesses\`, \`pages.model\` and \`assets.prompt\` are outputs of \`src/engine\` functions from a \`prospects\` row; regenerate, do not hand-edit.\n- **Tracking is one table.** Every interaction is an \`events\` row written by \`src/tracking/track()\`.\n\n## Tables (${tables.length})\n`;
for (const g of TABLE_GROUPS) { const list = tables.filter((x) => x.group === g.id); if (!list.length) continue; md += `\n### ${g.label}\n`; for (const t of list) { md += `\n#### \`${t.name}\`\n${t.description}${t.source ? `  \n_Source: ${t.source}_` : ''}\n\n| column | type | notes |\n| --- | --- | --- |\n`; for (const c of [...baseColumns(t), ...t.columns]) md += `| \`${c.name}\` | ${c.type}${c.enum ? ` (${c.enum.join(' \\| ')})` : ''}${c.nullable ? ', null' : ''} | ${c.references ? `-> \`${c.references}\` ` : ''}${c.description ?? ''} |\n`; if (t.access?.length) md += `\n**Access:** ${t.access.join('; ')}\n`; } }
md += `\n## Adding a table (module contract)\n1. Add a \`TableDef\` + typed row interface to \`src/data/schema/<module>.ts\` (\`index.ts\` globs it; never edit index).\n2. Seed it in \`src/data/seed/<module>.ts\` (exports \`seed(ctx)\`; \`ctx.ids.prospects\` holds the seeded prospect ids).\n3. \`npm run sql\` regenerates \`supabase/schema.sql\` and this file (the integrator runs it; note it in your \`_pending\` changelog).\n4. Reference it in the page's \`PageSpec.data\` so the inspector links to it.\n`;
writeFileSync(new URL('../docs/data-model.md', import.meta.url), md);
console.log(`wrote supabase/schema.sql (${tables.length} tables) and docs/data-model.md`);
